src/jsapi.c
src/luaapi.c
src/tic.c
src/tic.h
src/ticapi.h

added to js & lua
supports use_map ( i.e. render like a map )
supports chroma ( i.e. ignore color )

textri command

---

src/code.c
src/studio.c
src/studio.h

Nothing special: simply add a small button to run code.
It can help beginner and show CTRL+R shortcut

Run button on code editor

---

src/code.c
src/code.h
src/studio.c

Run button added in code editor buttons only.

Run button on code editor only

---

src/console.c

In an attempt to get to better know the code, I have added a simple feature that will help folks who want to check the version, who are also either full screened or don't have a window manager with window titles.
Feel free to close the PR if this feature is a waste of time.

Adding version command to console

---

src/tic.c

I tried to improve the speed of this function
The most common path has 25% speedup.
Other paths are also bit faster.
I hope the code is not less readable.

Speedup drawTile.

---

src/tic.c

Function takes half of the clock time.
pi3
before 0.741 ms per function call
after 0.335
pi2
before 2.145
after 1.070

Optimize api_blit inner loop.

---

src/tic.c

Clip the tile in all orientations.
Speed up blitting for scale=1.

Speedup drawTile 2.

---

src/tic.c

It creates 30% speed up on my desktop (this is not something spectacular, but I already wrote it and it doesn't spoil the code much).

Speed up of api_blit

---

src/sprite.c

Currently, if you press DELETE, the entire sprite is removed.
If you have a selection and press delete, everything is lost.
This PR checks if user has a selection. If so, it only removes the selected area.

Enable deleting a selection by pressing DEL on keyboard

---

src/machine.h
src/tic.c

2.4x speedup for Shapes test in Benchmark tic.

Speedup api_circle

---

src/tic.c

I haven't measured the performance change.

Use drawhline in api_tri.

---

src/machine.h
src/tic.c

I fixed one off errors for circle and tri.
I also squashed everything into single commit so revert would be easier.

Speedup api_circle, api_tri.

---

src/code.c

Adds support to indent or unindent, anywhere in the line, if user is pressing shift or crtl.
shift + tab will unindent.
crtl + tab will indent.
Fixes issue https://github.com/nesbox/TIC-80/issues/192

Add support to crtl or shift to indent/unindent anywhere in the line

---

src/sprite.c

Solves part of the issue https://github.com/nesbox/TIC-80/issues/103
Yet, it does not solve `rotate`, since it needs discussion.

Enable horizontal or vertical flipping of a sprite selection

---

src/sprite.c

Adds selection rotation.
Solves issue https://github.com/nesbox/TIC-80/issues/103
It rotates to the right (as the previous rotation used to do).
It also keeps the selection at the front, so we can keep rotating and moving the selection around.
The only downside now is, to get rid of the selection tool, we have to click the selection tool to disable it.

Rotate sprite selection

---

.gitignore
src/tic.c

saved some space, fixes wibbling across texture

Textri using constant slope and fixed point math 

---

src/tic.c

the occasional cracking is fixed .
moved the check for using map outside the inner pixel loop for speed up
removed the per pixel check for X in range as it's now fixed with the clipping above

textri clipping works .

---

build.sh

Added a menu for the build.sh script, that allows to select different targets.

Create menu for build.sh

---

src/tic.c

fixed UV errors

---

src/jsapi.c

Add true and false as JS Keywords

---

build/macosx/Info.plist
build/uwp/tic/Package.appxmanifest

Update version number for uwp and macosx

---

README.md

I was having some issues building in my system regarding requirements.
These seemed to solve them.

Update Ubuntu 18 build documentation

---

README.md

Fixed a few typos in the readme :D

fixed a few typos in the readme

---

src/luaapi.c

Show Moonscript compile time errors

---

src/luaapi.c

https://moonscript.org/reference/

Add using and local as moonscript keywords

---

CMakeLists.txt
build/android/jni/src/Android.mk
build/uwp/tic80/tic80.vcxproj
build/uwp/tic80/tic80.vcxproj.filters

Requires https://github.com/nesbox/3rd-party/pull/7

Update to Duktape 2.3.0

---

examples/sdl/main.c

This allows running...
```
bin/sdl-renderer demos/fire.tic
```

SDL: Allow providing a cart as a command line argument

---

CMakeLists.txt

This was submitted by `@r5` on Discord.

libretro: Fix MSYS2 building to /bin

---

src/system/libretro/libretro.h
src/system/libretro/libretro_core_options.h
src/system/libretro/retro_inline.h
src/system/libretro/tic80_libretro.c

This cleans up the core options to have a description to the opts.

Add libretro core options API

---

.gitignore

```
git status
On branch mousecursor
Untracked files:
(use "git add <file>..." to include in what will be committed)
demos/.local/
demos/fire.rtc
demos/fire.srm
demos/palette.rtc
demos/palette.srm
```

gitignore: Ignore state information for demos

---

src/system/libretro/libretro.h
src/system/libretro/libretro_core_options.h
src/system/libretro/libretro_core_options_intl.h

This allows for translations for the core options.

libretro: Update Core Options API

---

README.md
src/system/libretro/README.md

Use the build directory.
Reported by msx...
> Building for target : Linux
CMake Error at 3rd-party/sdl2/CMakeLists.txt:2 (message):
Prevented in-tree built.  Please create a build directory outside of the
SDL source code and call cmake from there

docs: Update build instructions

---

.gitignore

After compilation, running the following resulted in a bunch of the build assets. This pull requests adds them to the .gitignore...
```
git status -u
```

Add build assets to .gitignore

---

src/system/libretro/tic80_libretro.c

libretro: Hide mouse pointer after X seconds

---

CMakeLists.txt

Reverts nesbox/TIC-80#1010
Oops, the PR breaks build on Travis

Revert "Fix missing entry point error on Windows 7"

---

build/libretro/Makefile
build/libretro/Makefile.common
build/libretro/link.T

- We will maintain it if needed.

Add libretro Makefile

---

src/jsapi.c

This switches a bunch of the JS duktape functions to use `duk_opt_()` functions.
References https://github.com/nesbox/TIC-80/issues/1054

Switch to duk_opt_() functions

---

include/tic80.h
src/code.c
src/console.c
src/fs.c
src/history.c
src/map.c
src/music.c
src/net.c
src/player/sdl.c
src/player/sokol.c
src/sfx.c
src/studio.c
src/surf.c
src/system/libretro/tic80_libretro.c
src/tic.c
src/tic80.c

fixed some warnings from A static analyzer

---

src/tic.c

Map the color to draw as soon as it is known in order to avoid unnecessary swaps
- if possible, map color once in the api function
- if the color is sourced from memory, map color when source pixel is read
Internal single-color drawing primitives should only work with final colors
Api functions shouldn't call each other to avoid remapping more than once

Refactor internal use of palette mapping

---

src/studio.c

Draw studio popup after everything else

---

src/console.c

I have it set right now to not overwrite any existing file with that name.
Currently it saves into the TIC data directory rather than the current
directory; if you pass it an absolute path it fails; I believe the
path should be interpreted as relative to the current directory, but
I'm not sure how to accomplish this.

Allow "export html foo.zip" to provide name non-interactively.

---

src/system/libretro/.gitignore
src/system/libretro/README.md
src/system/libretro/libretro-common/include/libretro.h
src/system/libretro/libretro-common/include/retro_inline.h
src/system/libretro/libretro_core_options.h
src/system/libretro/libretro_core_options_intl.h
src/system/libretro/tic80_libretro.c

This cleans up how the libretro core handles the state, along with the memory management of the state objects.

libretro: Update state management

---

src/code.c

update editor upon backspace and delete
should fix #1167

update editor upon processing backspace

---

src/system/libretro/tic80_libretro.c

libretro: Fix segfaults around the state

---

README.md

Sometimes g++ is not installed

Added g++ to ubuntu 18 dependency

---

src/system/sdl/player.c
src/system/sokol/player.c

This updates the SDL player to add a bit of error reporting and usage help documentation.

SDL Player: Add constants and clean up error reporting

---

README.md

Sound missing when following build instructions in Ubuntu 18.04. See https://github.com/nesbox/TIC-80/issues/796

README.md: Update Ubuntu 18.04 build: Add sound

---

CMakeLists.txt
build/baremetalpi/Makefile
build/baremetalpi/README.md
src/studio/fs.c
src/studio/screens/console.c
src/system/baremetalpi/kernel.cpp
src/system/baremetalpi/syscore.h
src/system/baremetalpi/utils.cpp
src/system/baremetalpi/utils.h

See issue #912
I patched up the build as best as i could, it works now. There's still some issue on the filesystem access (biggest thing is that "cd" command doesn't work) but it boots, carts can be loaded, played and saved.
I've updated the build procedure [here](https://github.com/nesbox/TIC-80/blob/master/build/baremetalpi/README.md).

bare metal rpi build updated to latest TIC-80 and Circle

---

README.md
build/baremetalpi/README.md
build/baremetalpi/toolchain.cmake
src/studio/fs.c
src/system/baremetalpi/kernel.cpp
src/system/baremetalpi/syscore.h
src/system/baremetalpi/utils.cpp
src/system/baremetalpi/utils.h

Hi, i've corrected some minor stuff on the baremetal build, including the instructions in README. Also added myself in the credits as kindly suggested by nesbox. Thanks :)

minor cleaning on RPI baremetal build and Credits

---

src/system/libretro/libretro-common/include/libretro.h
src/system/libretro/libretro_core_options.h
src/system/libretro/libretro_core_options_intl.h
src/system/libretro/tic80_libretro.c

Small updates to the libretro header files, along with some small coding standards fixes.

libretro: Update libretro.h and code standards

---

src/system/libretro/tic80_libretro.c

This updates the libretro memory slots that are available within the TIC-80 memory.

libretro: Update the memory data slots

---

src/studio/editors/code.c

Hey, 
I saw there was something for 0.90 where there was a request to implement commenting over multiple lines, so I decided to take it up. Let me know if this works!
Thanks again!

Multiline Comments

---

src/studio/editors/code.c

Font fix on cart load

---

src/system/libretro/tic80_libretro.c

Recommendation from @leiradel.

libretro: Fix retro_get_memory_size()

---

src/system/libretro/libretro_core_options.h
src/system/libretro/tic80_libretro.c

@jdgleaver added a few features to the libretro core. This change cherry-picks those forwards to the upstream.
- Option to remove the screen border
- Gamepad Analog deadzone
- Emulated mouse pointer for devices without a mouse

libretro: Add features from jdgleaver

---

src/api/wren.c

Related to https://github.com/nesbox/TIC-80/issues/1415

wren: Add as and continue keywords

---

src/studio/studio.c
src/studio/studio.h

I added a `--version` command line argument as described in #1502.

Added --version command line argument

---

src/core/draw.c

(fix) ignore negative index passed to spr

---

src/studio/fs.c
src/studio/fs.h
src/studio/screens/console.c

(enh) errors when mkdir fails

---

README.md

Fedora build instructions

---

src/studio/screens/console.c

Some missing spaces in the help text and rephrasings I found while trying out TIC-80!

Add some missing spaces, and reword a few phrases

---

src/cart.c
src/core/core.c
src/core/io.c
src/core/sound.c

This is a libretro downstream change from @jdgleaver to fix the OpenDingux builds of TIC-80.

Fix OpenDingux builds

---

demos/luademo.lua

Resolves #387.
Once we agree on the template I'll modify all the demos (not just Lua)...  does this look good?

add default license, version, site tags to demos

---

src/studio/screens/console.c

I try to do this all the time, so it should probably work. :)

support CTRL-A, CTRL-E console editing keystrokes

---

.github/workflows/build.yml
CMakeLists.txt
build/android/app/build.gradle
build/android/app/src/main/AndroidManifest.xml
build/android/app/src/main/java/com/nesbox/tic/TIC.java
build/android/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
build/android/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
build/android/app/src/main/java/org/libsdl/app/SDLActivity.java
build/android/app/src/main/java/org/libsdl/app/SDLAudioManager.java

This PR updates the SDL2 submodule to fix the build problem reported at #1769.

Update SDL2 version

---

.gitignore
src/studio/net.c

When I run TIC-80 without the Internet, I get a segmentation fault

Fix crash when internet is disabled

---

README.md

Update fedora build instructions for latest release.
I did this in a docker container, so it may over-specify vs what comes with a base install but the base should just not install any already existing packages.

Update fedora build instructions

---

CMakeLists.txt
src/cart.c
src/core/core.c
src/core/io.c
src/core/sound.c
src/ext/png.c
src/studio/editors/code.c
src/tic_assert.h

This is the main part of DJGPP support as libretro core. We also need some changes from duktape (https://github.com/svaarala/duktape/issues/2472) and wren (https://github.com/wren-lang/wren/pull/1090)

Add djgpp support

---

README.md

Add credits for PR #1946

---

src/studio/screens/console.c

(fix) help api/cmd/usage is not exclusive

---

src/system/libretro/tic80_libretro.c

This is the follow up to my previous fix to make sure libretro works as well.

Fix counter and freq for libretro

---

.gitignore
src/studio/screens/console.c
src/studio/screens/menu.c

animation still a little glitchy.
[screencast](https://user-images.githubusercontent.com/74560659/210155223-4a1c0cbe-258e-455e-a64e-ba4643b8a70f.webm)

Skip empty menu option

---

README.md

Hey, I contributed this some time ago, I just noticed a path was wrong.
Cheers

Correct dev MacOS app path

---

src/api/janet.c

Based off the fennel outline function

Add janet outline function

---

README.md
src/api/janet.c

closes https://github.com/nesbox/TIC-80/issues/2108

update janet vendor, sandbox file (and everything else), implement OVR callback

---

src/api/scheme.c

Added error type and a callstack to the error message which greatly helps finding the error.

Better scheme errors

---

src/api/janet.c

- fixed off by one typo when looking at argc for sfx note data
- need to actually pull note, octave, and speed from sfx data if index is positive.
- Also added some panics on invalid sfx index, and channel values

fix implementation of janet sfx function

---

build/html/export.html
build/html/index.html

closes #2191 
Do we also need to adjust `build/webapp/index.html`? Im unfamiliar with how/where that's used, and its _slightly_ different then `build/html/index.html`
Heres a video of me clicking around with these changes 
[Screencast from 2023-05-26 11-15-39.webm](https://github.com/nesbox/TIC-80/assets/8620042/ad118383-3525-4be5-95a4-79ca15253f1f)

#2191 focus the canvas on click

---

README.md

The previous pr is https://github.com/nesbox/TIC-80/pull/2315
* support for octal and binary literals by @stautonico in https://github.com/blueloveTH/pocketpy/pull/154 a.k.a. `0x` and `0b`
* add better `str.format` by @numan947 in https://github.com/blueloveTH/pocketpy/pull/144
* add extra optimizations which improves overall performance by 10%
* improve `datetime` module and bug fixes
* fix a bug of `type.__class__`
* implement deque in C++ by @numan947 in https://github.com/blueloveTH/pocketpy/pull/155 now `deque` is much faster and powerful than before
* `list.sort` and `sorted` are stable now
* support `@property.setter`
* make `json.loads` accept bytes
* improve `defaultdict`
* add module `operator`
* make `str.split` faster when separator is a single character
This upgrade has no …

Upgrade Python language bindings to `v1.3.0`

---

src/studio/studio.c

fix horizontal scrolling when using trackpads.

---

src/system/sdl/main.c

Fix typo in max scale calculation

---

src/studio/editors/code.c

return 0 when pos is not a valid tab character for removeTab

---

src/studio/studio.c

to improve readability and at the same time make the compiler happy.

remove unsequenced modification and access

---

src/api/lua.c

I thought it was already added!

Add "self" to the lua syntax

---

src/studio/studio.c

#2444: fixed name for screenshots

---

src/studio/screens/console.c

my earlier pr was untested for 2 bpp. This branch fixes that issue so it imports correctly.

fix 2 bpp import

---

.github/workflows/build.yml

Does what it says on the tin :)

Fix missing dash in build.yml

---

src/studio/editors/sprite.c
src/studio/editors/sprite.h

#2526: added flags editbox

---

README.md

Per the title. Tested on Fedora 40 amd64 running in VirtualBox.

Readme improvements (Fedora 40)

---

.github/workflows/build.yml

Fix typo in build.yml

---

README.md

This was way more pain than expected but happy I got these two up-to-date and more detailed than before :)

Readme improvements for Windows

---

src/api/js.c

#2584: add 'of' js keyword

---

src/system/libretro/tic80_libretro.c

This change replaces the use of clock() with the frame time callback.

libretro: Replace clock() with frame time callback

---

src/system/libretro/tic80_libretro.c

This provides some minor changes to use `memset()` when initializing TIC-80, along with some tweaks in the mouse timer logic.

libretro: Use memset() to set the initial TIC-80 state

---

cmake/sdl.cmake

#2595: crash fix

---

debug-macos.sh
debug-windows.ps1

I've accumulated these two scripts because of all the test I've been doing. They are generic enough that they can be useful for others. Also saves me from copy-pasting them every time I create a new branch.

Debug scripts for Windows + macOS

---

src/studio/editors/code.c
src/studio/editors/code.h
src/studio/screens/console.c
src/studio/studio.c
src/studio/studio.h

The FFT patch is still work in progress, in the meantime, here is the Byte Battle patch that functions standalone without it either way.

Feature: Byte Battle

---

src/studio/screens/console.c

Mention reload argument in resume help text.

---

src/api/wren.c

Fixes https://github.com/nesbox/TIC-80/issues/2621.

Fix wren bindings

---

src/api/wren.c

Submitted by @Miguel-hrvs in #2621.

Fix `elli` and `ellib` bindings in wren

---

src/studio/editors/sprite.c

Fixes https://github.com/nesbox/TIC-80/issues/2514

fix sprite editor hotkeys when selecting

---

.github/workflows/build.yml

Fixes: https://github.com/nesbox/TIC-80/issues/2632

Fix ci 3ds and rpi builds

---

src/studio/editors/map.c

Continuation of this: https://github.com/nesbox/TIC-80/pull/2631

Fix changing tile in map editor changes tool for real

---

src/studio/editors/code.c

Fixes: https://github.com/nesbox/TIC-80/issues/2516

fix bookmarks include whitespaces at the beginning of the name

---

src/studio/editors/code.c
src/studio/studio.c
src/studio/system.h

Fixes: https://github.com/nesbox/TIC-80/issues/1986

Fix f1 hotkey conflict

---

src/studio/fs.c
src/studio/net.c

Fixes: https://github.com/nesbox/TIC-80/issues/2170

fix some strncat vulnerabilities

---

src/studio/studio.c

Fixes #2661. Draft because might fold it into #2663.

Fix issue with alt+1 on certain layouts

---

CMakeLists.txt
debug-linux.sh

Doing enough Linux things now that I've adopted my `debug-macos.sh` script for it.

debug-linux.sh

---

src/core/draw.c

fix incorrect rounding on negative texture coordinates

---

src/api/mruby.c

add scrollx and scrolly to ruby mouse()

---

.github/workflows/build.yml
build/baremetalpi/Dockerfile
build/baremetalpi/Makefile
src/system/baremetalpi/syscore.h
src/system/baremetalpi/utils.cpp

This adds support for the rpi5, and new board revisions. Also the docker image and toolchain got updated to be compatible with artifacts and checkout v4.

update to latest circle-stdlib

---

cmake/lua.cmake

Hello, this fixes #2754, #2555.

Fix deprecated features for lua/fennel

---

.github/workflows/build.yml
.gitmodules
cmake/pocketpy.cmake

The previous pr is https://github.com/nesbox/TIC-80/pull/2714 (8 months ago)
**Full Changelog**: https://github.com/pocketpy/pocketpy/compare/v2.0.1...v2.1.0
https://github.com/pocketpy/pocketpy/releases
* fix win32 clang build by @trim21 in https://github.com/pocketpy/pocketpy/pull/317
* avoid undefined behavior signed int overflow by @trim21 in https://github.com/pocketpy/pocketpy/pull/318
* fix pybind11 implementation for error_already_set by @KevinEady in https://github.com/pocketpy/pocketpy/pull/321
* add pybind11 implementation for module reload by @KevinEady in https://github.com/pocketpy/pocketpy/pull/324
* Improve memory managements (mem-v2) by @blueloveTH in https://github.com/pocketpy/pocketpy/pull/327
* implement `array2d.chunked_array2d[T, TContext]` by @blueloveTH in …

Upgrade Python language bindings to `v2.1.0`

---

debug-linux.sh
debug-macos.sh
debug-windows.ps1

Mostly the `-DCMAKE_POLICY_VERSION_MINIMUM=3.5` thing, other misc fixes.

Fix debug scripts

---

build/android/app/src/main/AndroidManifest.xml

[Android] Associate .tic files to TIC-80 app

---

build/android/app/src/main/AndroidManifest.xml
build/android/app/src/main/java/com/nesbox/tic/TIC.java

[Android standalone] fix association of .tic and .png to TIC-80 app
