- .gitignore
- src/code.c
This was done by implementing these functions and adding them to `processKeydown()` in `code.c`:
```c
static void goCodeHome(Code *code);
static void goCodeEnd(Code *code);
```
A simple thing that I thought was missing from the code editor.
> adding code editor ctrl+home and ctrl+end functionality

- src/map.c
I don't know if this feature is desired but I wanted to dig a bit in TIC-80 implementation.
The tile position label was not entirely visible when hovering the tiles
near the top/right of the screen.
This modification ensures that the label is always visible by moving it to
the opposite side of the tile if there is not enough space to display it
on the default position.
> Ensure tile pos is always visible in map editor

- src/console.c
just put the `watch` before `strcmp(param, "-code")` as suggested in the previous PR
> just that small micro-optimisation suggested in previous PR

- src/ext/duktape/duktape.h
- src/fs.c
- src/fs.h
These two commits clean up most of the warnings that gcc is spitting out. I'm not usually in the habit of patching libs, but this was especially annoying.
I'm still learning more about the source code, so feel free to ask for changes or close PR.
> Warning Cleanup

- src/sfx.c
- src/sprite.c
- src/studio.c
- src/studio.h
Im trying to solve issue https://github.com/nesbox/TIC-80/issues/455.
When copying a hex palette from the web, it may contain spaces, tabs or carriage commands (\r or \n).
Pasting it on TIC-80 will not work, making the users' life difficult (they have to fix the string in an editor).
This commit enables pasting hex palettes with blank spaces.
PS: it has been more than 10 years since the last time I wrote a single line in C. Please, let me know if Im making really noob mistakes.
> Remove whitespaces when pasting a new palette

- src/studio.c
- src/tic.c
Hide mouse when the input tag in the header is set to:
--input: keyboard
--input: gamepad
> Don't show mouse if we don't use it for input.

- src/sprite.c
After flipping a selection, when we try to move it, TIC-80 was getting the previous seleciton back and then moving it.
> Fix flipping a selection then trying to move it

- src/studio.c
While I was in the process of creating this patch I discovered the `Alt-1` thru `Alt-5` shortcuts, so maybe this one is redundant, but I thought it might be a nice shortcut to have. Feel free to close if you think it's unnecessary.
> Use ctrl-pageup/pagedown to cycle thru modes.

- src/luaapi.c
This allows to print tracebacks in lua and simplifies debugging.
> Add debug library for lua.

- src/console.c
This would close issue #549. I find it useful for quickly opening the wiki. It also shows new users that the wiki exists.
> Added "wiki" command to open github wiki in browser

- include/tic80_config.h
Currently, tic80_config.h checks to see if the project is being built on macOS but not iOS using `#ifndef TARGET_OS_IPHONE`. This doesn't work correctly because `TARGET_OS_IPHONE` _is_ defined on macOS, it's just defined to 0 instead of 1. So, the correct check is `#if TARGET_OS_IPHONE`.
This PR fixes that, which makes export (and probably other things) work again in builds on macOS.
> Fix failing #ifndef TARGET_OS_IPHONE check when building for macOS

- README.md
- src/console.c
- src/jsapi.c
- src/luaapi.c
- src/ticapi.h
- src/wrenapi.c
I have this working as a new command in console.c. I named it "eval"
so that it can be extended with other languages in the future. However
I think some of this code belongs in a different file. Maybe luaapi.c?
It feels wrong to be calling `lua_*` functions directly from here. Let
me know if you have a suggestion for how to improve this or if I'm
wrong and it's fine where it is.
Also, I haven't used the C API for Lua enough to know whether this is
correct use of the stack; I'm guessing that unless we call
`lua_settop(lua, 0)` the values from the code that's run (or the error
message string) would be left on the stack? Is `lua_settop` the right
way to clear out these values and ensure they get GCed?
The problem with moving the dostring code to another file is that I'm
not sure how you …
> Add eval command

- src/tic.c
Fixes both spr() and map()
Test with
```lua
function TIC()
poke4(2 * 0x03ff0 + 8, 14)
cls(9)
spr(1, 0,0, 14, 3,0,0, 2,2)
end
```
> Respect palette map for sprite colorkey

- src/system.c
I wanted to set an optional parameter (for example `-uiscale`) and specific cartridge when initialize time on `wasm`.
Then I wrote the following code in Javascript.
```javascript
<script type="text/javascript">
var Module = {
canvas: document.getElementById('canvas'),
arguments: ["tetris.tic", "-uiscale", "1.5"]
};
</script>
```		
However, it couldn't work as my expected. An optional parameter was worked but didn't boot the cartridge.
I investigate the cause then found it. This p/r is my proposal.
My idea is that if `argc[1]` has `.tic` to suffix, we judge to it was given a cartridge.
Please take a look if you have time.
Regards.
> Can set parameters and specific cartridge through arguments option.

- src/studio.c
- src/system.h
- src/system/sdlgpu.c
src/system/sdlgpu.c start
the studioInit is called before SDL_CreateWindow
so the goFullscreen wont get a valid window ID ,makes the fullscreen not working at all
so seperate the goFullscreen from studioInit and call it after SDL_CreateWindow
everything works now
> fix -fullscreen

- Dockerfile.dapper
This pull request adds a `Dockerfile.dapper` which builds TIC-80 on an Ubuntu 18.04 Docker container using [dapper](//github.com/rancher/dapper).
Build instructions:
1. Download [dapper](https://github.com/rancher/dapper#installation).
2. `$ git clone http://github.nesbox/TIC-80 --recurse-submodules`
3. `$ dapper`
Binaries will be located at `bin/`, as always.
> Allow Docker (dapper) builds

- src/sprite.c
A fix for a little bug, #586.
I didn't change the actual arguments in order to keep consistency with `floodFill()`, which receives inclusive coordinates. Hope it helps!
> Fix colour replacement misses borders

- src/console.c
One of the biggest problems I ran into when working on [my latest game jam entry](https://technomancy.itch.io/this-is-my-mech) was that the only way to make changes to the game state without restarting the whole game was `eval` which only takes a line at a time. I wanted to be able to reload my code and resume without wiping game state.
This patch implements that; when it detects that it is in "watch" mode, it automatically reloads all the game's code when you run `resume` in the console.
However, I'm not convinced that watch mode is the right way to determine whether to reload or not. For codebases that aren't written specifically to support reloading (that is, they do not preserve state in globals to keep them around between loads) resuming can act more like a full reset, which defeats …
> When --watch flag is passed, reload all the code upon resume.

- CMakeLists.txt
This prefixes any relative path with a CMAKE_SOURCE_DIR, so that path resolution works when building from a different directory.
> cmake: Fix directory resolution

- CMakeLists.txt
Is there a feature from CMake 3.9 that we need? Could we use 3.3? This will help with the NES Mini build.
From madmonkey.
> cmake: Update CMake minimum version to 3.3

- CMakeLists.txt
- src/system/libretro/libretro.h
- src/system/libretro/tic80_libretro.c
This does a few things for the libretro core...
- Fix the Mouse pointer API
- Flip the keyboard state so that both left and right shift can be recognized
- Add the proper suffix for Android build
- Persistent Memory (saves)
> libretro: Update mouse/keyboard, Android, Persistent Memory

- CMakeLists.txt
- src/studio.c
The compiler was complaining about a potential buffer overlow error, so I switched it to use snprintf instead, and then silenced the warning.
> Silence buffer overflow compiler warning

- src/system/libretro/tic80_libretro.c
This allows passing a string of PMEM index value pairs through the [RetroArch cheat system](https://www.libretro.com/index.php/upcoming-retroarch-1-7-4-cheat-code-searchingcreation-interface-with-rumble-features/).
Example:
- [Dangerous Dave.cht](https://github.com/libretro/libretro-database/blob/master/cht/TIC-80/Dangerous%20Dave.cht) gives you the ability to reset your life count to 3
- [8 Bit Panda.cht](https://github.com/libretro/libretro-database/blob/master/cht/TIC-80/8%20Bit%20Panda.cht) allows unlocking levels
> libretro: Add Cheat Code support

- src/system.h
This is needed to compile TIC-80 with studio on a C++ environment (similarly to how it's done in tic80.h)
> Extern C switch on studioInit

- src/music.c
so now the tracker behave more like other traditional music trackers.
> adding extra keys for the trackers

- .gitignore
After building TIC-80 in the `build` directory, you're left with `build/3rd-party`. This adds that directory to the .gitignore so that it doesn't appear when running `git status`.
> Fix .gitignore to ignore build/3rd-party

- src/luaapi.c
This updates the syntax highlighting for new keywords in Fennel.
It also disables "strict globals" mode to make it more forgiving like Lua.
One question: it appears that the file `demos/fenneldemo.tic` is supposed to be loaded when you run `new fennel`. However, the actual contents that get loaded are slightly different; there is a stray `>` character that is not there in the `demos/` file. In addition the number passed to `cls` is different. Do you have any idea which file needs to get updated to fix this?
> Fennel 0.3.0 syntax

- src/map.c
- src/world.c
- When trying to select across the edge of the map, the selection
rectangle no longer jumps and stretches across the entire map.
The mouse coordinates were being normalized prior to expanding the
selection extent, so for example a 1,1 start point and a -1,-1 end point
would evaluate to 1,1..W-1,H-1, turning a 2x2 selection into the entire
map!.
It's actually fine for the selection rectangle to go outside the valid
range because the copy/paste functions all normalize the individual
gets/sets.
- Don't allow scrolling into negative offsets in the world view. This
breaks the grid drawing code temporarily when you switch back to the
map.
- When the map rectangle wraps around in the world view, draw all the
wrapped quadrants. This makes it clearer how the map wraps around and
avoids "losing" …
> Map view fixes when wrapping around the edge

- src/code.c
- Ctrl+backspace, Ctrl+delete delete adjacent words.
- Ctrl+x without selection cuts the entire line. Previously
it was implemented but buggy; it copied the line but didn't have a
selection to replace.
- Outline match supports non-consecutive forward matches, for
instance "dph" will match "drawPlayerHit". Matching characters are
highlighted in the outline view.
> Misc code editor additions/fixes

- CMakeLists.txt
1. Disable shared SDL build, fixes various _fltused linker errors when building the DLL.
2. Make Sokol build WIN32 in Debug (never CONSOLE) because sokol_app defines WinMain, not main. Fixes linking tic80-sokol under VS2019.
It would be possible to retain the Debug-is-CONSOLE by defining SOKOL_WIN32_FORCE_MAIN as a PUBLIC compiler flag for the sokol library, but this would require changes to player-sokol.
Also, some minor formatting changes which helped me understand the file.
> Fix MSVC build issues

- src/system/sdlgpu.c
When switching away from TIC-80, the OpenGL context is destroyed by the
system and needs to be recreated along with all resources (textures and
shaders).
SDL2 makes an attempt to save and restore the active GL context when
pausing and resuming the activity, but it fails on my device, and the
Android and SDL2 documentation indicate that it's a best-effort feature.
Because the keyboard and gamepad images are lost when the textures are
destroyed, backing buffers are allocated to store them when they are
first filled out.
Additionally, SDL_gpu needs to be fully destroyed and recreated to
resolve the problem on my Pixel 3a XL. Just recreating the textures and
shader and calling GPU_ResetRenderState is not enough.
(Ideally, this entire problem is something that would be handled by
the SDL_gpu …
> Fix Android black screen when paused

- src/system/sdlgpu.c
Hi, this is two separate changes to the touch keyboard. They can be separated and taken independently if you want. 
The first is some usability stuff I encountered - making the keyboard appear at startup and after resume, and squelching the keypress that makes it appear.
The second is an issue I saw people talking about in Discord and is a pretty straightforward bug.
> Touch keyboard tweaks and fix

- CMakeLists.txt
When SDL is disabled, don't attempt to build the SDL player.
> cmake: Fix build when SDL is disabled

- src/system/libretro/libretro_core_options.h
- src/system/libretro/tic80_libretro.c
This change makes it so that by default, it will use the Mouse API instead of the Pointer API. While Pointer API is great, it's less supported across different libretro implementations.
> libretro: Flip mouse pointer device logic

- src/jsapi.c
- src/luaapi.c
- src/squirrelapi.c
- src/system/libretro/tic80_libretro.c
- src/wrenapi.c
This adds `scrollx` and `scrolly` support to `mouse()` for the mouse wheel information (horizontal/vertical).
Fixes #988
The following example is taken from @StinkerB06 cart for testing....
[mouse.tic.zip](https://github.com/nesbox/TIC-80/files/4194529/mouse.tic.zip)
``` lua
-- title:  Input reader
-- author: StinkerB06
-- input: mouse
function TIC()
local x,y,left,right,middle,scrollx,scrolly=mouse()
print("X: "..tostring(x), 1, 40, 4, 0, 2)
print("left: "..tostring(left), 1, 60, 4, 0, 2)
print("ScrollX: "..tostring(scrollx), 1, 80, 4, 0, 2)
print("ScrollY: "..tostring(scrolly), 1, 100, 4, 0, 2)
end
```
Once merged, I can update the wiki documentation.
> Add ScrollX and ScrollY to mouse()

- CMakeLists.txt
The Duktape library invokes a function, GetSystemTimePreciseAsFileTime,
that was added in Win8.
This simply changes the build configuration to use a less precise
function. Hopefully this doesn't impact timing in any games.
> Fix missing entry point error on Windows 7

- src/system/sdlgpu.c
Fixes #587. When using the SDL backend, cursors were created every frame but not being freed by [`SDL_FreeCursor`](https://wiki.libsdl.org/SDL_FreeCursor) (in fact they were not even tracked at all). This led the [Xorg server cursor memory](https://www.x.org/wiki/Development/Documentation/CursorHandling/) to fill up and never be freed, ending up requiring restarting X.
This issue did not happen when using the Sokol backend.
[`xrestop`](https://www.freedesktop.org/wiki/Software/xrestop/) makes it easy to figure this leak out, while `tic80` is running
```bash
$ xrestop -b -m 1 | grep -A 15 'TIC-80' | grep cursors | cut -d: -f 2 | xargs
824 # before fix, increased _a lot_ every frame, would end up in gigabytes of memory used
$ xrestop -b -m 1 | grep -A 15 'TIC-80' | grep cursors | cut -d: -f …
```
> Fix SDL cursors memory leak

- CMakeLists.txt
Apparently it has some weird conflict
> Don't add -s USE_SDL=2 with libretro-emscripten

- src/system/libretro/tic80_libretro.c
This will check if the frame buffer is set before clearing it. Will save from causing a segfault on cores that call callbacks in the wrong order.
> libretro: Protect freeing an empty frame buffer

- src/jsapi.c
- src/luaapi.c
- src/machine.h
- src/squirrelapi.c
- src/tic.c
- src/ticapi.h
- src/wrenapi.c
This adds a `timestamp()` function to allow grabbing the [Unix timestamp](https://en.wikipedia.org/wiki/Unix_time) in seconds. This would allow making persistent games by storing the timestamp in `pmem()`, and then calculate elapsed time between game runs.
``` lua
currentTime = timestamp()
```
Fixes https://github.com/nesbox/TIC-80/issues/841
timetamp    -> The current unix timestamp in seconds.
* **seconds** : the number of _seconds_ that have passed since January 1st, 1970. 
This function returns the number of _seconds_ elapsed since January 1st, 1970. Useful for creating persistent games which evolve over time between plays.
``` lua
-- title: timestamp demo
elapsed = -1
function TIC()
cls(15)
-- Display the current time stamp
current = timestamp()
print('Timestamp: ' .. current, 10, …
```
> Add timestamp() function

- build/libretro/Makefile.common
- http://paste.libretro.com/201007
- was working on my pc using gcc version 9.3.0...
> Fix libretro Makefile

- src/jsapi.c
Fixes #1052
Would appreciate some testing on this one!
> Fix font() breaking when retrieving arguments

- src/music.c
- src/music.h
Hi! :)
First of all, congratulations for your work with TIC-80, I've been in love with it recently.
So I've changed the behavior of the cursor in the editor. Now, when you play a track or a frame, the editor will scroll with the cursor allowing you to see what's currently being played. I made this behavior true by default.
I also changed how the editor follows the cursor. Before, the cursor was always at the bottom/top of the editor when scrolling, now it's always at the center. That's default [for](https://www.youtube.com/watch?v=Dmhtc5S4atU) [most](https://www.youtube.com/watch?v=mD6F3b2GiFc) [trackers](https://www.youtube.com/watch?v=B_IQ709vIuo).
One last thing, I also added a shortcut to toggle follow mode: CTRL + F.
> Follow cursor on music editor

- src/tic.c
This fixes the bug discussed at https://github.com/nesbox/TIC-80/issues/1059#issuecomment-620431392
The change seems to only affect `tic_api_tri` and `tic_api_line`, effectively fixing the discrepancy caused by point order sensitivity.
> Sort points vertically in ticLine

- src/code.c
- src/code.h
When you're in the code editor, this will make it so having your cursor over a `(` character will highlight the matching `)` character. (or similarly with `[`/`]` and `{`/`}`). This makes it much easier to avoid syntax errors.
The highlighting uses `rectb` around the matching delimiter with the same color as the cursor, so it is visually similar to the cursor but more subtle.
I could also add a config setting to allow you to disable this feature, but I haven't done so yet; do you think this is a good idea?
Fixes #1075.
> Highlight matching delimiters in code editor

- src/code.c
built on current master.
In the code editor, trying to highlight a matching delimiter in the following code will cause segmentation fault.
```lua
func())))))
```
findMatchedDelim may return NULL, which should instantaneously break out of the loop and avoid dereferencing a NULL pointer when checking for the loop condition.
Also, the `current` pointer should probably be bound by TIC_CODE_SIZE (it currently isn't and looks like it can go outside of the code memory segment).
> Fix segmentation fault caused by findMatchedDelim unsafe NULL pointer

- src/console.c
I was thinking it might be nice to be able to export to HTML from my makefile. I have two commits here to make that happen; the first one makes it so the CLI accepts a `-command foo` flag which gets run as a console command, and then exits. As far as I can tell this works. The second commit attempts to make it so that the console command `export html foo.zip` will use "foo.zip" as its output filename instead of popping up a system save dialog box. This part does not work yet.
Anyway, if you think this is a good idea I can continue to work on this and get the problems ironed out, but if you think this complicates things too much that is fine too; I wanted to ask your opinion before I spent much more time on it.
Thanks!
> Accept and run commands from argv.

- src/jsapi.c
- src/luaapi.c
- src/map.c
- src/squirrelapi.c
- src/start.c
- src/system/sdlgpu.c
- src/tic.c
- src/ticapi.h
- src/wrenapi.c
> Enable chromakey array on map and textri

- src/console.c
This fixes the functionality introduced in #1101 so it can accept any path rather than saving inside the data directory.
Also show a more useful error message when the file already exists.
> Export based on current directory, not internal data folder.

- src/studio.c
- truncate popup message to buffer size in `showPopupMessage`
- truncate filename and add truncation placeholder in `saveProject`
> Fix popup buffer overflow with long filenames

- src/jsapi.c
This isn't really that pretty, but does display the lineNumber.... References #1113
Alternatively, we could get the linenumber by using....
``` c
// If thrown is a valid error message, retrieve the stack for it.
if(duk_is_error(duk, -1) == 1)
{
duk_get_prop_string(duk, -1, "lineNumber");
machine->data->error(machine->data->data, duk_safe_to_string(duk, -1));
duk_pop(duk);
} else {
machine->data->error(machine->data->data, duk_safe_to_string(duk, -1));
}
```
We would have to make sure we have the error message in there too though, which would need some concat strings.
> Display the stack when there is an error

- src/surf.c
- src/tic.c
* surf will now no longer try to draw lines outside of render range (this *really* helps when browsing the TIC-80 website list on low-end hardware in particular)
* drawVLine now checks clipped boundaries instead of screen size for early cancellation
* some methods received an EARLY_CLIP check behind potentially expensive for loops (I'm not sure on this one, what are your thoughts?)
> minor rendering optimizations

- include/tic80.h
- src/studio.c
- src/system/baremetalpi/kernel.cpp
- src/system/baremetalpi/size.h
- src/system/baremetalpi/stdlib_app.h
- src/system/baremetalpi/syscore.h
- src/system/libretro/tic80_libretro.c
- src/system/sdlgpu.c
- src/tic.c
- src/tic.h
- src/tic80.c
- src/ticapi.h
- src/tools.c
- src/tools.h
Allows for natively outputting to the buffer in a format different than
the default SDL/Sokol one. This also means that the libretro port now
avoids an additional conversion step.
More or less necessary for the 3DS port.
> Add pixel color format field to TIC-80 structs and blitting.

- .gitignore
- src/player/sokol.c
- src/system/sokol.c
This allows the function `time` to return valid values by implementing `getPerformanceCounter` and `getPerformanceFrequency`:
https://github.com/drako0812/TIC-80/blob/42f685cc3d0b06036a756017644f48c68462ebd1/src/system/sokol.c#L79-L87
I don't like how I had to return a raw value for `getPerformanceFrequency`, but `sokol_time` doesn't provide a convenient way to query this information.
It seems to work just fine, but I'm not 100% sure I put the call to `stm_setup` in the right spots.
Currently `stm_setup` is called:
here
https://github.com/drako0812/TIC-80/blob/42f685cc3d0b06036a756017644f48c68462ebd1/src/system/sokol.c#L167
and here
https://github.com/drako0812/TIC-80/blob/42f685cc3d0b06036a756017644f48c68462ebd1/src/player/sokol.c#L45
Also the modifications to `.gitignore` could be …
> fixes #1163 (0.80 beta) time() always returns 0 when built with sokol

- src/system/libretro/libretro-common/include/libretro.h
- src/system/libretro/libretro_core_options.h
- src/system/libretro/tic80_libretro.c
This adds a Mouse Cursor Hide Delay option, to configure the number of seconds to wait before the mouse is hidden.
> libretro: Add Mouse Hide Delay option

- .gitignore
After building, compile_commands.json ends up showing in git status. This change ignores that file.
> gitignore: Ignore compile_commands.json

- src/studio/studio.c
This saves `video1.gif` or `screen1.gif`, and increments the index when one is already saved.
Fixes #1275
> Allow multiple screenshots and videos to be saved

- README.md
I tried to simplify the instructions to make it better fit with the existing README build instruction style.
Original can still be found:
https://github.com/nesbox/TIC-80/wiki/Build-instructions
After this is merged I'll update the wiki fully.
> (chore) Migrate Raspberry Pi build instructions from wiki

- src/studio/screens/console.c
Changes in the interest of clarity and being a bit more explicit.  This follows from the work I already did on the Wiki.
- "FONT" => "SYSTEM FONT"
- K => KB
- Adds VRAM to the RAM map (seems important and that VRAM exists inside of RAM)
- Adds "reserved" and "free" comments for clarity
- SIZE => BYTES
- "BORDER" => "BORDER COLOR"
> Make RAM and VRAM a bit more explicit

- .gitmodules
Fixes #1323
https://github.com/svaarala/duktape/blob/master/doc/release-notes-v2-6.rst
> Update to Duktape 2.6.0, and use a shallow clone

- src/system/sdl/main.c
- src/system/sokol/sokol.c
As I noted in issue https://github.com/nesbox/TIC-80/issues/559#issuecomment-770119463, mouse values wrapped around when moving the mouse towards the edges of the screen, especially in fullscreen.
The problem is that the mouse's x/y values are stored as 8bit after being written in RAM.
One possible fix is to clip the values _before_ writing them into RAM, which is what I did here. The mouse's x values are now clipped to a range of 0 to TIC80_FULLWIDTH-1 (and 0 to TIC80_FULLHEIGHT-1 for y) before written into ram.
This is basically identical to the clipping/checking already done in n3ds and in libretro:
https://github.com/nesbox/TIC-80/blob/acddaaad3ae5f5f403db9f1a69872697fb49efb5/src/system/n3ds/main.c#L497-L508
https://github.com/nesbox/TIC-80/blob/acddaaad3ae5f5f403db9f1a69872697fb49efb5 …
> Clip mouse values in SDL and Sokol

- README.md
Is this supposed to be well hidden?  Why would someone building from source (possibly contributing to the project, etc) not want the pro version by default?  Could all the build instructions be updated to build pro or explain how?
This was not clear at all and took me like 10 minutes to figure out.
> Show how to build pro version

- src/studio/screens/console.c
Since a39a206 (File Sytem refactoring, 2020-02-02) using cmdLoadCart()
results in a cart name containing the full path passed instead of only
the basename.
Fix by making it possible for isslash() to return true ("warning C6288:
Incorrect operator: mutual inclusion over && is always zero. Did you
intent [sic] to use || instead?"), and skipping copying of a path
separator.
> Fix using full path as cart name when loading cart

- CMakeLists.txt
Not sure if this will impact other functionality, I did try surf after I built this and it looks like it worked fine.
> Fix MinGW build, do not add msvc specific flag

- src/api/wren.c
Two fixes for the Wren's API
1. `TIC.btn()` was not defined in Wren and had the wrong return value
2. `TIC.btn(_)` was mixing controllers 1 & 3, 2 & 4
Fixed 2 problems:
1. The handler `wren_btn` was checking for this call but it was not declared as part of the `TIC` class and it was not defined in `foreignTicMethods`
2. The handler `wren_btn` was setting the return value to `bool` instead of `double`
The button index _bitmask_ was `0xf` instead of `0x1f`, this made tat gamepad 3 returned value for gamepad 1 and gamepad 4 returned value for gamepad 2.
> Wren TIC.btn fixes

- src/api/squirrel.c
The "fixed" flag was being read from arguments 5, where it actually is in arguments 6.
> Fixed Squirrel's print function fixed flag

- src/studio/screens/console.c
Looked like `code` was missing from the import list, so I've opted to add it and alphabetize the list.
> Add "code" to the import usage documentation

- Dockerfile.dapper
This changes are now in sync with the manual build instructions. Building successfully in Ubuntu 21.04 and macOS Catalina 10.15.7 (19H524), though the binary executable it's only valid for Linux.
PS: Maybe it is possible to integrate Github actions with this file.
> fix dapper builds

- README.md
Apparently the `jessie-backports` repo was moved to archive.debian.org
> Update jessie-backports repo location

- src/studio/screens/console.c
The import command was broken since the switch to use `split()` and `strtok()` for parsing the command parameters. This PR makes import work again.
> Fix import command.

- src/studio/screens/console.c
I ran into these SIGSEGVs when trying to load any cartridge on CentOS Stream 8.
After adding the null checks the cartridges load without a hitch.
#0  0x00007ffff69aa685 in __strlen_avx2 () from /lib64/libc.so.6
#1  0x00007ffff68d6802 in strdup () from /lib64/libc.so.6
#2  0x000000000043bca2 in onLoadCommandConfirmed ()
#0  0x00007ffff69aa685 in __strlen_avx2 () from /lib64/libc.so.6
#1  0x00007ffff68d6802 in strdup () from /lib64/libc.so.6
#2  0x000000000043b8ea in loadByHash ()
> Fixes for 2 SIGSEGVs when section is NULL

- src/studio/screens/console.c
Hi there. I spotted this in some user-facing text, thought I'd ask for it to be corrected.
> Correct spelling of a single word

- README.md
This PR adds documentation on installing and running TIC-80 using the Linux build instructions.
The original docs didn't mention running `sudo make install` to install the program.`make -j4` is executed while running `sudo make install -j4`  so the former is redundant and has been removed.The docs also didn't mention how to run the program after installation so those instructions have been added as well.
The `make -j4` in the Mac build instructions could also be replaced with `sudo make install -j4` but I don't have a MacOS machine to test it on so somebody else could try that.
> Installing and running instructions

- src/studio/editors/map.c
In the Map Editor, use **ctrl+click** while in FILL mode to replace a specific tile with another tile across the whole map (or only in the selection).
This *Replace Tile* feature also works with rectangular sprite patterns.
The pattern is offset based on the mouse click position.
https://user-images.githubusercontent.com/10946971/125296665-cea34100-e326-11eb-9d5d-8ca4da13f92e.mp4
Fixes #764
> #764: replace tile feature in map editor

- src/system/sdl/player.c
``` bash
[100%] Building C object CMakeFiles/player-sdl.dir/src/system/sdl/player.c.o
/home/rob/Documents/TIC-80/src/system/sdl/player.c: In function ‘runCart’:
/home/rob/Documents/TIC-80/src/system/sdl/player.c:134:23: warning: comparison of integer expressions of different signedness: ‘s32’ {aka ‘int’} and ‘long unsigned int’ [-Wsign-compare]
134 |     for (s32 i = 0; i < SDL_arraysize(Keys); i++)
|                       ^
```
> sdl: Fix comparision warning

- src/system/libretro/tic80_libretro.c
- src/tic.h
This fixes the warnings generated in the libretro implementation, and adds a `TIC_UNUSED()` define to fix warnings from `-Wunused-parameter`.
For example...
```
TIC-80/src/system/libretro/tic80_libretro.c:1186:41: warning: unused parameter ‘index’ [-Wunused-parameter]
1186 | RETRO_API void retro_cheat_set(unsigned index, bool enabled, const char *code)
|                                ~~~~~~~~~^~~~~
```
> Add TIC_UNUSED() to handle unused parameter warnings

- src/studio/fs.c
It was missing some passages throu tic_fs_path to normalize the path.  I've tested it and it seems ok now.
> fix path problems with baremeta #1541

- CMakeLists.txt
- include/tic80_config.h
- src/api.h
- src/api/js.c
- src/api/lua.c
- src/api/squirrel.c
- src/api/wren.c
- src/core/core.c
- src/core/core.h
- src/core/languages.c
- src/studio/demos.c
- src/studio/demos.h
- src/studio/project.c
- src/studio/screens/console.c
Developments for discussion #1289.
Changes: there's now a new file "languages.c", this is the designed place to "glue" all languages together. It defines a "Languages" global array of tic_script_config where all enabled languages go.
tic_script_config has been augmented with stuff that was defined in other places, like file extensions, demo and bunny mark cartridges, etc. (every implementation defines the new fields).
Most of the accesses with SCRIPT_LIST has been removed in favour of a loop on Languages (for which a macro is provided).
The static help text problem has been resolved by inserting placeholders in the static text and replacing them with a dynamic strings at runtime. It's terribly inefficient but since we're talking of a handful of lines, it should be ok. At least it works …
> Improvements for language support

- build/baremetalpi/Makefile
- build/baremetalpi/toolchain.cmake
Hi there, when i added Baremetal RPI i left out Squirrel becouse the toolkit was having trouble linking C++ stuff. I checked this again and found the problem: i simply wasn't setting C++ compiler flags (only C ones).
Now the baremetal version include all languages, and also any future C++ dependency we add will be able to work.
> Baremetal RPI: added Squirrel language which was previously disabled.

- src/studio/screens/console.c
This fixes issue #800.
I am not 100% sure this is in line with the original intent of the fields, and I have very little C experience!
The CommandDesc struct has two relevant fields here: src and
command. The src field is supposed to contain the source of the entire
input while the command field is supposed to contain just the name of
the command being invoked; aka everything before the first space.
We would start with input like this:
eval trace("hello" .. "world")
What we want is:
src: eval trace("hello" .. "world")
command: eval
The src field was set to a copy of the input, and then the command
field was set to running strtok on src to find the first space. But
even though strtok returns what looks like a string, it's actually
just pointing to the same copy of src which now happens to …
> Fix eval command

- src/api/lua.c
Previously, the tic_core* was associated with a global variable named "_TIC80". Finding the global variable with that name took surprising amount of time, according to profiling. With this optimization, each API function is associated with tic_core* through lua_pushcclosure mechanism. Closures are functions that are associated with certain "upvalues". Fetching an upvalue is very fast in LUA.
> Optimize tic api call performance in LUA.

- src/api.h
- src/core/core.h
- src/core/sound.c
- src/studio/studio.c
- src/system/sdl/main.c
Previously, the sound registers were used to synthesize fixed amount of sound after every TIC() and this was pushed to SDL. The problem with this approach was crackling if TIC() takes too long to reach 60Hz. In this fix, the sound registers are instead pushed to a ring buffer and the audio is synthesized in SDL callback, to render audio. If the ring buffer does not have enough values, the sound synthesis uses the last good values from the ring buffer, so the music slows down yes, but at least it does not crackle.
The corollary to this is that calling tic_core_tick_end(tic) is not enough during the Studio sound export; one should also call tic_core_synthesize_sound which does the job of pulling the sound registers from the tail of the ring buffer and doing the sound synthesis.
The ring …
> #714: fix crackling audio.

- src/api.h
- src/api/js.c
- src/api/lua.c
- src/api/squirrel.c
- src/api/wren.c
- src/core/core.c
I think these would be useful, especially for compact single-bit flags in save files.
> Poke1 and Peek1

- CMakeLists.txt
- src/api/lua.c
- src/api/lua_api.h
- src/api/moonscript.c
- src/api/squirrel.c
- src/api/wren.c
Feels like every language should have their own C file in `api`... so I wonder if this should be broken out?
> (chore) move moonscript into separate C file

- src/studio/editors/music.c
Allows toggling of sharp.  I guess technically it doesn't even require you to be in the column...
Resolves #1625.
> (enh) Music editor: Skip over sharp column when using cursor keys

- README.md
Sup,
I am playing around with MacOS as well and launching the development version is a bit weird via Spotlight (it creates a terminal window by default). So here are instructions for hackers who would like to launch it conviniently.
I tested this on my latest MacOS (Monterey is it called?) and I noticed you guys provide also a DMG which installs as "tic-80" so I renamed this to be "TIC-80dev" so people can have both stable and dev versions installed and switch between each other.
Cheers.
> add MacOS application instructions

- CMakeLists.txt
- src/studio/project.c
- src/studio/project.h
- src/studio/screens/console.c
- src/tools.c
- src/tools.h
> suggest pro when trying to open source with standard

- src/api.h
The former doesn't render correctly when "help map" is issued in the console.
> Replace a right single apostrophe in the API help with an apostrophe

- CommunityGuidelines.md
Because the additional "moderated community" sentence was added to README.md, and to keep TIC-80 friendly for non-adults.
> Add community guidelines

- src/api/squirrel.c
Looks like Squirrel's `push` methods will append to the array. Since the array was initialized with `7`, the values were already initialized as null, and the mouse values were appended to the end. This fixes that.
Fixes #1718
> squirrel: Fix mouse() from returning null values

- src/api.h
- src/api/fennel.c
- src/api/js.c
- src/api/lua.c
- src/api/moonscript.c
- src/api/mruby.c
- src/api/squirrel.c
- src/api/wren.c
- src/studio/editors/code.c
This is a convenience feature shamelessly stolen from PICO-8: when pressing Shift+Return in the code editor, insert an `end` statement, and put the cursor in an indented line in-between. For example, we go from
for x=0,239 do|
to
for x=0,239 do
|
end
I would love to use this during speedcoding! Is this a welcome feature? Does this PR look alright?
> Add Shift+Return shortcut to the code editor that auto-closes a block

- src/studio/screens/console.c
I noticed that there was a space behind each language option, leading to an improper-looking list in the CODE section of `help spec`. Before:
After:
Also seems to fix the indentation, I didn't touch that. Implemented in the most straightforward way I could think of, does that seem alright?
Also removes the last "|..." in `help new`, as I don't think there are other options, right? Before:
After:
> When listing language options in the spec, use "x, y, or z" format

- src/studio/screens/console.c
> On Linux, use Ctrl+L to clear the console, per default of other shells

- src/studio/screens/console.c
As per #1746, this is an implementation attempt.
The help for the keys is arranged in two columns to save some space:
Open questions:
- Should the topics be mentioned in the help texts for `btn(p)` and `key(p)`? I think probably not – for example, `poke` also doesn't mention the RAM and VRAM pages.
- Should the tables have headers, like RAM and VRAM?
- Should they be included when exporting the help?
> Add help topics for keys and buttons

- src/studio/screens/console.c
> Console: `cd` with no args returns home

- demos/bunny/jsmark.js
- demos/bunny/luamark.lua
- demos/bunny/moonmark.moon
- demos/bunny/rubymark.rb
- demos/bunny/squirrelmark.nut
- demos/bunny/wrenmark.wren
- demos/fenneldemo.fnl
- demos/jsdemo.js
- demos/moondemo.moon
- demos/rubydemo.rb
- demos/squirreldemo.nut
- demos/wrendemo.wren
> (chore) bring all Demo header into sync with new tags

- src/core/core.c
- src/core/core.h
- src/studio/studio.c
Resolves #1785.
This fix captures the current (`input.ram.keyboard`) state in
`tick_start` and immediately restores it in `tick_end`. This
prevents cartridges from injecting corrupt "previous" states
into the keyboard state engine that could be used to hijack
keyboard input.
When we trust `input.ram.keyboard` after user code has run
we open ourselves up to a cartridge:
- repeating keyboard events by fake "lifting" a key
(which is still held by the user, then registering as
separate repeating keypress/releases until the user
finally releases the key)
- preventing key up events by fake "holding" a key
(this prevents the state engine from ever seeing the
key release).
---
Originally this was a lot larger, but I figured it was going to be too hard to review and certify with just a glance. …
> fix: prevent cartridges hijacking keyboard events

- src/studio/screens/console.c
Since we have so many different languages, wouldn't it be nice to encourage users to experiment with each of them and find out whatever fits them the most instead of defaulting to Lua?
We could either not have a default language at all (this "patch") or put some reminder that other options are available to try as well.
> Do not default to the first available language for new carts.

- src/core/draw.c
Resolves #1796 .
`drawTile` appears to be taking clipping into account, yet in
setPixel for every single pixel we check the clipping
individually... it seems this is not necessary.
This adds a new `setPixelFast` that avoids the repeat checks.
I see about a 4-5% increase in benchmarks for just sprite draws.
> faster drawTile, remove repeat clipping checks

- src/core/languages.c
If we aren't playing favorites anymore then this order really should be alphabetical, not historic.
> order langauges by alphabetical order

- src/studio/screens/console.c
I'd appreciate code review/feedback/help on this! I'm building better tab-completion, which is aware of the different commands. It knows how to complete files, directories, help topics, commands, and the import/export types:
Implementation notes:
- Console commands get two callbacks for autocompleting their first/second option. Both can be null when they don't take parameters.
- An `AutocompleteData` struct keeps track of the word the user is trying to tab-complete, the options that have been gathered so far, as a string, and the longest common prefix of all options, in order to add it to the typed command later.
- An `addAutocompleteOption` adds a possible completion option to the struct.
- In the end `finishAutocomplete` is called to actually perform the tab-completion, its shows all …
> [WIP] Advanced tab-completion for the console

- src/api/wasm.c
- templates/d/Makefile
- templates/d/README.md
- templates/d/build.sh
- templates/d/buildcart.sh
- templates/d/buildwasm.sh
- templates/d/dub.json
- templates/d/src/main.d
- templates/d/src/tic80.d
- Add Makefile and dub.json for D.
- Improved README.
- Fix function signature type mismatches.
Fixes #1888.
> Improved D template

- src/studio/editors/code.c
In Code Editor, we can scroll the the code with cursor keys.
For example, if the cursor is at the end line of the screen and if we press down arrow key,
the code will scroll up.
We also can move the cursory by pressing several key-combinations like Ctrl-P, Ctrl-N, Ctrl-E, Alt-Left, Alt-Right.
On the other hand, the key-combinations does not scroll up/down.
This PR will enable the scrolling with the key-combinations.
> Enable scrolling Code Editor by key-combinations like Ctrl-P and Ctrl-N.

- CMakeLists.txt
- README.md
These instructions and changes allow to build the project on FreeBSD 13.0-RELEASE-p11.
I tested a few games, and everything seemed to work, including audio.
I could not find where the path to `swrast_dri.so` is defined, so I just added a note to the `README.md` about it.
> Building on FreeBSD

- build/linux/com.tic80.TIC_80.metainfo.xml
- build/linux/tic80.desktop.in
Hi,
This PR adds metainfo file which contain information that might be useful to end user such as description, links, screenshots, etc. It is useful when TIC-80 is put is an app store such as Flathub for Linux which display these infos.
I name it as `com.tic80.TIC_80.metainfo.xml` so it would conform to reverse DNS scheme and dash is replace with underscore as recommended here:
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#file-naming
I change the `Categories=education` in desktop file to` Categories=Education` because it is case-sensitive as mention here: 
https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry
I would also like to submit TIC-80 to Flathub, which allow linux user to install it very easily, let me …
> Add metainfo and fix case typo in desktop category.

- src/cart.c
An old note on the wiki mentions a bug that occurred when saving and loading a 65536 byte `CODE` chunk, and this has since been fixed. The bug also applies to `BINARY` chunks, so I've extended the original fix to cover those as well.
> Fix loading full-size BINARY chunks

- src/studio/editors/sprite.c
- src/studio/editors/sprite.h
currently when drawing in tic80's sprite editor, only the point at the current mouse position is "stamped", which leads to undesirable gaps in the user's stroke:
this pull request changes the behavior to draw a line between the previous mouse position (now cached as a member of the Sprite struct) and the current one, resulting in an unbroken stroke:
hopefully this change is useful, if there is anything that I should change please feel free to let me know, too.
> Add smooth line drawing in sprite editor

- templates/zig/README.md
- templates/zig/src/main.zig
- templates/zig/src/tic80.zig
As mentioned in https://github.com/nesbox/TIC-80/issues/1784#issuecomment-1171940804, I found a few problems with the current Zig template.
With this PR, there is no longer an example of using the raw API, as I couldn't come up with a suitable structure that supported multiple examples without duplicating tic80.zig. I don't think this is a major issue though, as I imagine most users of the WASM templates will use the wrappers anyway.
> Improve the Zig template

- build/android/app/src/main/AndroidManifest.xml
- build/android/app/src/main/java/com/nesbox/tic/TICDocumentsProvider.java
In Android 11 and later, file access from the other app got strict.  So we cannot edit files under the home directory of TIC-80.
This PR will enable to edit source code file under the home directory of TIC-80 by any Android text editor with Storage Access Framework.
https://developer.android.com/guide/topics/providers/document-provider?hl=en
These screenshots are of the file open dialog of a text editor app (Jota+).  I confirmed that I can edit hello.rb with the app and then the editing result is affected by pressing Ctrl-R on TIC-80.
I expect this PR might solve some part of #1540
> Add DocumentsProvider for Android.

- build/android/app/src/main/AndroidManifest.xml
- build/android/app/src/main/java/com/nesbox/tic/TICFileReceiver.java
In Android 11 and later, file access from the other app got strict.  Though the PR #1998 enabled to edit exiting file in the home directory of TIC-80, we cannot still put files (PNG files and source code files) from outside of TIC-80.
This PR will enable to place such files in the directory by using intent ACTION_SEND.
The first screenshot is of "Files of Google" app, and the second one is of dialog of TIC-80 when receiving a file.
I confirmed that the app can send both a PNG and a Ruby source code to TIC-80, and that "Google Photo" app can also send a PNG.
I expect this PR might solve #1540 combining with #1998.
> Add receiving intent of ACTION_SEND for Android.

- src/system/sdl/main.c
The problem as it stands, there's no way to emulate an insert press on a Macbook keyboard, which makes composing music on the TIC-80 a little tricky. 
fn+backspace works fine as 'delete', but support for fn+enter is sporadic at best and for some reason it is equivalent to SDLK_KP_ENTER. So, this change just enables fn+enter as an insert keypress on Mac versions of the application.
> Support fn+enter alias for insert on mac keyboards

- src/studio/studio.c
- src/studio/system.h
- src/system/baremetalpi/kernel.cpp
- src/system/n3ds/main.c
- src/system/sdl/main.c
- src/system/sokol/sokol.c
TIC-80's uiScale currently defaults to 4. This turns out to be a poor choice for everybody's favorite maybe-still-supported platform, the PocketC.H.I.P., which lacks a screen large enough to accommodate it.
For whatever reason (maybe [issue 1904](https://github.com/nesbox/TIC-80/issues/1904)?), recent TIC-80 builds also perform very badly at scale 4 on the PocketC.H.I.P., taking more than a minute to start up and then missing many keystrokes.
I recorded the image above after twice failing to "exit". Note that the cursor is not visible.
Additionally, sound is currently broken for TIC-80 on the PocketC.H.I.P. (but not for other SDL2 applications.) That is not a big problem by itself, but will complicate the implementation of a screen-framing fix slightly.
A sophisticated user can circumvent …
> override some scale settings; finer-grained SDL init

- src/api.h
- src/core/core.c
- src/core/core.h
- src/studio/screens/run.c
- src/studio/system.h
- src/system/baremetalpi/kernel.cpp
- src/system/n3ds/main.c
- src/system/sdl/main.c
- src/system/sokol/sokol.c
- src/tic.c
Resolves #1904.
Pretty much a revert of just the time/clock specific portions of 3dc2feacbeb2f1db8e7184eb548d381d7e690efc.  This returns to using per kernel functions for getting the system time and frequency.
Not exact (but I'm betting it's never been exact).
> (fix) fix `time()` API call - revert the `clock()` changes

- src/system/sdl/player.c
Sometimes player-sdl segfaults during shutdown. By reordering the shutdown sequence the segfault seem to have disappeared.
> Fix rare segfault during shutdown

- include/tic80.h
- src/system/libretro/tic80_libretro.c
- src/system/sdl/player.c
- src/tic.c
There is a bug in that tic80_tick doesnt set up the counter and freq callbacks properly which leads to a segfault.
This is probably not a good solution and it only works for player-sdl and the same issue is probably also in libretro which needs a proper fix too.
> Fix segfault in player-sdl

- build/tools/xplode.c
- src/ext/png.c
- src/ext/png.h
- src/studio/screens/console.c
As explained in isse #2042 steganography has certain limitations. This patch add support storing the cartridge data in `caRt` PNG chunk as well. For backward compatibility, it still tries to use steganography if the cartridge fits into the pixels, and on load if no `caRt` chunk found, still tries steganography.
> Adding png chunk cartridge support

- src/studio/screens/console.c
Remove the error "unknown topic" when typing `help api` and similar help commands.
> Don't show "unknown topic" when help message is displayed

- src/cart.c
This small patch is a follow up on https://github.com/nesbox/TIC-80/pull/2045 that fixes the issue https://github.com/nesbox/TIC-80/issues/2048
The patch adds chunk loading to cart.c, meaning libtic80cora.a will be able to load png cartridges even without the editors or when compiled for libretro (and possibly other systems).
Cheers,
bzt
> Add png chunk loading

- src/api/janet.c
suggestion comes from the creator of janet themselves!
> The garbage collector will eventually try to call free(&errBuffer), which will segfault. janet_buffer_init is mean to be used with janet_buffer_deinit
> -bakpakin
> make errBuffer pointer, avoid memory bug by not using janet_buffer_init

- src/api/wren.c
> add function definitions for music args count 4 through 7

- src/studio/screens/menu.c
- src/studio/screens/menu.h
- src/studio/studio.c
I was tired of having to navigate to close the editor when there were changes so I made this change ;p
> Added hotkey option to menu items. Used in Yes/No dialog.

- src/api.h
- src/api/lua.c
- src/api/scheme.c
- src/studio/editors/code.c
Added 'stdStringStartEnd' option in tic_script_config to allow language to define their tokens to start/end strings.
> Language specific string delimiters

- src/studio/editors/code.c
When a line is deleted (ctl+k) it is also added to the clipboard, like it does in emacs. This is very conveniant.
> Delete line improvement

- src/api/scheme.c
Found that bug while using the scheme api in a local project.
> fixed error in scheme SPR api function

- src/api/wasm.c
Solves https://github.com/nesbox/TIC-80/issues/2131.
This enables calling `map()` from the WASM API with sx or sy=-1, which is consistent with the Lua API. 
This does not break any of the current languages with templates (C, D, Rust, Zig) because arguments to `map()` cannot be omitted. However, for future languages which allow optional arguments, this may require workarounds at the language API level to get sx/sy=0 by default, if `m3ApiGetArg()` defaults to -1 on missing arguments (I do not understand how `m3ApiGetArg()` works, but the other defaults in wasm.c seem to assume a `int32_t` with a value of `-1` from `m3ApiGetArg()` means a missing argument).
> Remove defaults for sx/sy in WASM map() function

- src/api/fennel.c
In 6171e0d0644ec68908e3478926a1b90b04cec3c1 a bug was introduced which disabled strict mode for newly-created Fennel carts, because strict mode is activated by the presence of ";; strict: true" in the cart's headers, but that commit broke it by adding an extra space after the colon.
See https://github.com/nesbox/TIC-80/blob/main/src/api/fennel.c#L41
If we could ignore backwards-compatibility, it would be better to fix the check so it would be tolerant of spaces.
However, since this bug was introduced before the release of 1.0.2164, carts may have been created using the stable release that have the extra spaces in the header but are not actually compatible with strict mode. So fixing the strict mode check would cause those carts to no longer be playable.
Rather than breaking backwards …
> Fix strict mode in default fennel cart.

- src/api/fennel.c
This updates the list of Fennel keywords to match all the new forms
introduced in 1.3.0 since the last time.
Also overrides the definition of a word constituent character to match
the language semantics; based on Scheme's but with a few changes.
Also enables structured editing for Fennel carts; love this feature.
> Update list of Fennel keywords for version 1.3.0.

- src/api/fennel.c
In Fennel 1.3.0, it checks to see whether `_G.io.read` exists before proceeding with friendly compiler error messages, because it used to have to read the source from disk in order to provide these messages. That is no longer needed; it can use the source provided as a string, but the check for `_G.io.read` was accidentally left in place.
This change bypasses that check with a fake io table in order to get improved compiler error message and parse error reporting.
It should be removed once Fennel 1.3.1 or 1.4.0 is brought in.
We also set the error pinpointing characters to `>>` and `<<`. In normal Fennel, these use ANSI escape codes to change the color when writing to the terminal, but TIC-80 does not support these escape codes. I think it would be better if we could change the color of …
> Bypass checks which disable Fennel friendly compiler errors.

- src/studio/studio.c
Fixes https://github.com/nesbox/TIC-80/issues/1913.
animEffect() seems to expect a value between 0 and 1, and #1913 is caused by the surf coverFade animation lerping past 1, which feeds values greater than 256 into fadePalette(), causing the flashing colors. This PR clamps movie ticks for each item ensuring animEffect won't receive values > 1.
This could create issues if any animation items rely on playing past their end. I didn't notice any while visually checking the editor and surf menu animations, but I could easily have missed something.
It might be better to move this clamp directly to the start of animEffect().
Alternative fixes for #1913 include clamping the fadePalette() value between 0 and 256, or stopping the animation at the right time.
> Clamp input to animEffect()

- src/api/janet.c
currently pmem is not actually setting new values, and always returns garbage. 
```janet
(print (tic80/pmem 0)) # observe garbage number
(tic80/pmem 0 123)
(print (tic80/pmem 0)) # nope still garbage
```
> fix janet pmem implementation, which was completely broken.

- src/studio/screens/console.c
- src/studio/studio.c
- src/studio/studio.h
This commit fixes the bank parameter for exporting music (see issue #2190).
There is still some ambiguity present, because the exported music depends on the sfx bank as well. 
If bank chaining is on, the exported music uses the same sfx bank as the music bank.
If bank chaining is off, the exported music uses the sfx from the currently active sfx bank.
This could be fixed by introducing a `chained=true/false` parameter for the export.
> Fix bank parameter for music export

- README.md
Following the instructions as-is leads to the plist executable pointing to a different executable than what is created from the heredoc script. Renaming the script file fixes it
> Update macOS build instructions to match included plist file

- src/studio/editors/music.c
I noticed the keyboard shortcuts in the music tracker using the ctrl key did not work. Turns out the code was never called if ctrl was pressed.
Moved the key processing in music tracker out of the `!ctrl` scope.
Added early exit from `processPianoKeyboard()` if ctrl or alt keys are pressed, which mirrors the way it's done in `processPatternKeyboard()`.
> Run key processing even when ctrl key is pressed

- demos/pythondemo.py
This is the more common syntax and it is PEP 8 compliant.
Although PEP default indentation width is 4, the default indentation width of TIC-80 is 1, so this commit changes it to 1. As is typical for TIC-80's brevity, this commit removes spaces after commas as well.
https://peps.python.org/pep-0008/
> Remove whitespaces before colons in pythondemo.py

- templates/rust/README.md
It turned out, that a new WASM cartridge must be created prior to saving a new one, in order to prevent the default Lua code running, instead of the WASM code.
> #2260: Updated Rust template build instructions

- src/api/janet.c
I think `withsyms` is missing a `-`.
This PR adds a '-'.
> Change janet's withsyms to with-syms

- .gitignore
- src/studio/editors/code.c
Fixes #2293 . Structured editing is disabled in non-Emacs editors by checking the editor mode in `shouldUseStructuredEdit()`.
I also added a root-level  `compile_commands.json` line to the `.gitignore` file, as `clangd` requires the file to be in the root to be detected correctly.
> Disable structured editing on non-Emacs editors

- demos/bunny/wasmmark/build.zig
- demos/bunny/wasmmark/src/main.zig
- demos/bunny/wasmmark/src/tic80.zig
- demos/wasm/build.zig
- demos/wasm/src/main.zig
- demos/wasm/src/tic80.zig
- templates/zig/README.md
- templates/zig/build.zig
- templates/zig/src/main.zig
- templates/zig/src/tic80.zig
The previous Zig `build` and `tic80.zig` files built fine with Zig 0.10, but no longer build with the latest _stable_ (0.11) nor the current development version (0.12). 
This PR updates the Zig examples so that they build with both 0.11 and 0.12 😄 
I've also formatted the files in question with Zig's language server formatter.
> Update zig examples and template to latest Zig

- src/api/fennel.c
Fixed #2302 . This PR adds `true`, `false` and `nil` to FennelKeywords, in order to make those words be in a different color in the editor.
Before PR:
With PR:
Feel free to ask any questions! :D
> Add true, false, nil to FennelKeywords

- src/api/js.c
As described in issue 2291, the code to handle the colorkey parameter in the spr function did not use the correct default value in one of the two code paths.
We now pass the correct default value to getInteger2, this handles cases where the parameter is not present, and where the parameter is `undefined` in JS.
> Fix issue 2291

- src/studio/editors/code.c
This commit adds the following key bindings:
- Ctrl + '_': undo
- Ctrl + '<': beginning of document
- Ctrl + '>': end of document
These are all standard Emacs key bindings.
> Add a few more emacs bindings

- src/api/janet.c
[From reading the wiki](https://github.com/nesbox/TIC-80/wiki/ttri)
> texsrc : if 0 (default), the triangle's texture is read from SPRITES RAM. If 1, the texture comes from the MAP RAM.
If 2, the texture comes from the screen RAM in the next VBANK (the one following the VBANK on which the ttri() is set to be displayed) (e.g., a ttri() on vbank(0) with the texsrc=2 will use vbank(1) as its texture at the time of its execution). Although there is technically no vbank(2), this can be used on a ttri() with texsrc=2 that's rendered on vbank(1).
Looks like this was added to the lua api [in this commit ](https://github.com/nesbox/TIC-80/commit/8586bc183ca7652ea1835a061f6308dc91061b36) and I just missed it
> Janet language bindings for ttri fn, texsrc arg can be int or bool

- src/api/mruby.c
fixed issue: eval causing the program to crash when no cart is running; vm being mistakenly reset when calling eval so resuming is impossible; potential memory leak
> fixed eval command in ruby

- src/api/mruby.c
`trace` in lua accepts object-type argument. so should ruby be
> `trace` can log object-type argument in ruby to be consistent with lua

- src/studio/editors/music.c
- src/studio/editors/sfx.c
Slightly changed the keyboard in the SFX editor so that it became more similar to the popular DAWs (Ableton, Garage Band, etc...)
1. Added the ability to switch between octaves on Z and X
2. Raised all the shortcuts one row higher (A, W, S, E, D, ...)
3. Increase the number of possible notes that can be played on the keyboard
> Increase in possible notes for playing on piano roll, new keyboard layout (like in popular DAWs)

- src/api/python.c
Change `print` into `print(text, x=0, y=0, color=15, fixed=False, scale=1, alt=False)`.
Fix https://github.com/nesbox/TIC-80/issues/2338.
> [Python] Fix incorrect signature of `print`

- templates/zig/README.md
- templates/zig/build.zig
> [!IMPORTANT]
> Related to the breaking changes in https://github.com/ziglang/zig/pull/17815
This requires `0.12.0-dev.1482+e74ced21b` or later (currently the latest `master` release on https://ziglang.org/download/ is `0.12.0-dev.1516+a70d8d29d`)
> zig: Replace `addSharedLibrary` with `addExecutable`

- src/api/wasm.c
I noticed two issues in `src/api/wasm.c` when trying to call `pmem` from a small [Zig](https://ziglang.org/) :zap: program (compiling to `.wasm`)
- `writeToStorage` was never set to `true` _(unless I've misunderstood the code that is)_
- The signature of `wasmtic_pmem` indicated that the arguments would be three 32 bit values: `i(ii)`, and not two 32 bit (return value and `address`) + one 64 bit value (for `value`) as I expected: `i(iI)`
Related to issue #2360
> api/wasm: `writeToStorage` defaults to `true`, update `wasmtic_pmem` signature from `i(ii)` to `i(iI)`

- src/api/python.c
The previous pr is https://github.com/nesbox/TIC-80/pull/2353 (3 weeks ago)
1. fix a bug of type names
2. improve f-string. It supports `{{` and `}}` escape now
3. rename easing functions. Now names are like `easing.Linear` and `easing.OutQuad`
4. allow complex assignment in class definition
5. add `str.splitlines()`
6. fix https://github.com/blueloveTH/pocketpy/issues/179
7. add `csv` module
`v1.3.1` introduces `csv` module with `csv.reader` and `csv.DictReader` for parsing csv files.
The module is a compatible subset of cpython's `csv` which supports common csv format with linebreaks.
```python
import csv
def test(data: str, expected):
ret: list = csv.reader(data.splitlines())
assert ret==expected, f"Expected {expected}, got {ret}"
test("""a,b,c
1,2,3
""",  [['a', 'b', 'c'], ['1', '2', …
```
> Upgrade Python language bindings to `v1.3.1`

- src/studio/screens/console.c
Hello, haven't ever made a pull request before. Also exploring around this project is my introduction to C lang... memory management stuff completely soars over my head. I have very little idea of what I'm doing.
I forked the project a while ago in hopes of making a visual update to Surf called Launcher. Going for the tile-based look. I had some fun tinkering with it, and made a bit of progress, however I keep running into Segmentation Faults and other such errors. Whole original reason is that I'm planning on picking up the Retroid Pocket 2S this holiday. I read around the discord to see if others ever tried using it for tic80 and from what I saw; it's rough at first, mainly because of tic80 being oriented to a keyboard-console. Makes sense. Once people manage to get into the Surf menu …
> Gamepad shortcut to Surf

- src/system/sdl/main.c
The SDL2 metal backend has performance issues that is widely reported elsewhere (such as https://stackoverflow.com/questions/59700423/why-is-sdl-so-much-slower-on-mac-than-linux). By opting to the OpenGL backend, TIC-80 uses much less CPU cycles than before and achieved higher benchmark score.
> Use OpenGL backend for macOS

- src/studio/editors/code.c
Fix #2394.
PR #2376 made an incorrect fix to #2358 and #2335, and this PR simply revert changes in `code.c` back to previous version.
> Fix horizontal scrolling when press the shift key

- src/studio/editors/music.c
to make compiler happy so it no longer warn about missing switch cases.
> enumerate all music tab values in switch

- .gitignore
- src/studio/config.c
- src/studio/screens/console.c
- src/studio/screens/console.h
- src/studio/screens/mainmenu.c
- src/studio/screens/surf.c
- src/studio/screens/surf.h
- src/studio/system.h
Hello again for my second pull request ever. This time I actually searched through pull requests and issues first to see if my idea has previously been denied lol.
While waiting until Christmas to possibly get the Retroid Pocket 2S, I've been using tic80 more with just a controller and my phone. I encountered another difficulty, and that is keeping games for offline play. Currently if you like a game you found on Surf and you want to play it later without internet; you have to close it then use the keyboard to name/save it locally. Using the app Unexpected Keboard (available on fdroid) this isn't too bad, and once again fits in logically with the keyboard/console design. However if your device is small and can barely accommodate a keyboard this quickly becomes too much.
Here I added an …
> Autosave option for keeping carts from Surf

- src/api/python.c
`tic_api_time` returns a `double`, not an `int`, so it should push a `float`, not an `int`.
> Update Python's time() to return a float instead of an int

- src/core/core.c
Calling `memcpy` with overlapping source and destination buffers is undefined behaviour. For example, see #1875. But, users of the _TIC-80 `memcpy` function_ probably expect it to work fine even with overlapping buffers. Thus: `memmove`.
> Use memmove in tic_api_memcpy

- templates/rust/README.md
Without `--target=wasm32-unknown-unknown` there is no `wasm32-unknown-unknown` folder and we get a file not found.
> add `--target=wasm32-unknown-unknown` to README.md

- src/api/python.c
The previous pr is https://github.com/nesbox/TIC-80/pull/2382 (2 weeks ago)
* improve f-string performance
* add support for `\b`
* add `issubclass()` builtin
* support class decorator
* add a new module `dataclasses`
* fix a bug when users are trying to create `module` instance
* fix a bug about `**kwargs` in function call
* fix a parser bug of f-string such as `f"{stack[2:]}"`
* `class` can be used in normal blocks now
```python
from dataclasses import dataclass, asdict
@dataclass
class A:
x: int
y: str = '123'
a = A(x=2)
b = A(3, y='AAA')
print(a)    # A(x=2, y='123')
print(asdict(b))    # {'x': 3, 'y': 'AAA'}
```
> Upgrade Python language bindings to `v1.3.5`

- CMakeLists.txt
- include/tic80_config.h
Currently TIC-80 supports so many programming languages. While this gives game developers a lot of flexibilities, it has a few shortcomings not limited to larger binary size and longer build time. Most of the languages are not actively used. Some of those languages' developers are not actively developing / maintaining their languages anymore. TIC-80 is also not supporting all languages equally so features are missing here and there. From security perspective bundling in all those languages is also not ideal. 
I decide to make most languages optional so user can configure the build process. Not sure if you agree on this proposal so for the first PR I am only doing it for a single language. If this PR gets accepted I can continue to work on other languages.
> Make WREN a configurable build option.

- cmake/core.cmake
- cmake/janet.cmake
- cmake/lua.cmake
- cmake/mruby.cmake
- cmake/pocketpy.cmake
- cmake/quickjs.cmake
- cmake/scheme.cmake
- cmake/squirrel.cmake
- cmake/stub.cmake
- cmake/tools.cmake
- cmake/wasm.cmake
- cmake/wren.cmake
- include/tic80_config.h
- src/api/fennel.c
- src/api/janet.c
- src/api/js.c
- src/api/lua.c
- src/api/moonscript.c
- src/api/mruby.c
- src/api/python.c
- src/api/scheme.c
- src/api/squirrel.c
- src/api/wasm.c
- src/api/wren.c
- src/core/languages.c
and removed definitions from `tic80_config.h`
> Added cmake build options for all the supported scripts

- src/studio/screens/console.c
Makes `rm` a console alias for `del` for people who prefer unix-style commands
> Add "rm" as an alias for "del"

- src/studio/screens/console.c
only tested with BPP 1. requries that the pngs still use the same colors as the in game pallete.
> Add BPP arg to sprites import

- src/studio/screens/console.c
Currently, the console doesn't indent (offset) the continuation of a wrapped line if wrapping coincides with with a '|' or a space character. This is  demonstrated in the output of `help spec`:
```
DISPLAY 240x136 pixels, 16 colors
palette.
INPUT   4 gamepads with 8 buttons /
mouse / keyboard.
SPRITES 256 8x8 tiles and 256 8x8
sprites.
MAP     240x136 cells, 1920x1088
pixels.
SOUND   4 channels with configurable
waveforms.
CODE    64KB of lua, ruby, js, moon,
fennel, scheme, squirrel, wren,
wasm, janet or python.
```
Above, the last (continuation) line is not indented because the line break coincides with the space (' '), right before `wasm,`.
This makes the console indent all wrapped continuation lines (so the final line of `help spec` is also indented).
> console: Indent all wrapped lines

- templates/rust/src/tic80.rs
All other options structs have their fields public, so these should too (otherwise you can't construct them directly).
> Makes Rust template `PrintOptions` and `FontOptions` structs fields public

- src/core/core.c
- src/core/core.h
- src/core/sound.c
- src/studio/screens/console.c
- src/tic.h
Thanks to the discussion https://github.com/nesbox/TIC-80/discussions/2487 I added playback of PCM channel.
You can assign 128 PCM samples at every TIC() function and play sound with a quality of 7680hz (128 * 60).
A very simple example of JS to generate a sin wave using PCM
```js
// script:js
let t=0
function TIC()
{
cls(13)
for(let i=0;i<128;i++)
poke(0x14E24+i,(Math.sin(t*128+i)+1)*127)
t++
}
```
> PCM sound channel

- .github/workflows/build.yml
GitHub has runners now for macOS 14 / arm64 so we can have native builds from the CI.
> Compile for MacOS arm64 in CI as well

- src/studio/screens/console.c
When using tab completion with `load`/`save` in a folder with a lot of files, or really anything that'd result in an output longer than `CONSOLE_BUFFER_SCREEN`, TIC-80 would crash. This is due to `data->options` of TabCompleteData overflowing and not being null-terminated.
Create 100 blank `.tic` files:
```
#!/bin/bash
mkdir repro && cd repro || exit 1
for i in {001..100}; do
touch "test-$i.tic"
done
```
Start TIC-80 with the `repro` folder as its base: `./build/bin/tic80 --fs ~/repro`
Type "load<tab>" and it'll likely crash. maybe not at first, but after a few tries at most, definitely.
This was a hell of a bug to track down, but also a fun one that made me learn `lldb` and `ASAN`. I have some other PRs coming soon about that.
I have a few suggestions for future improvements and PRs:
* …
> Fix tab-completion crash with load/save/etc.

- CMakeLists.txt
While tracking down the bug in https://github.com/nesbox/TIC-80/issues/2448, besides a billion debug `printf`s I got myself acquainted with [`lldb`](https://lldb.llvm.org/) and [`AddressSanitizer`](https://clang.llvm.org/docs/AddressSanitizer.html) which were extremely helpful finding said bug.
To make the debugging process easier I added a few options to `CMakeLists.txt`:
* `BUILD_NO_OPTIMIZATION` — adds `-g -O0`
* `BUILD_ASAN_DEBUG` — adds `-fsanitize=address -fno-omit-frame-pointer`
I have yet to try its sister [`LeakSanitizer`](https://clang.llvm.org/docs/LeakSanitizer.html); gave a go for [`UndefinedBehaviorSanitizer`](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) but too many things fail on it currently, starting with external dependencies.
To get TIC-80 to compile …
> Add various debug options to CMake

- .gitmodules
AddressSanitizer errors out with the `glew` library in `sdl-gpu` unless it's updated.
I took the version/commit hash you used currently for `sdl-gpu`, forked it and updated `glew` to its latest version from its git `master` branch.
Updating `sdl-gpu` itself would be a much bigger endeavor as there are many breaking changes.
As far as I could test it, things work fine with the updated version.
Related to https://github.com/nesbox/TIC-80/pull/2533 and https://github.com/nesbox/TIC-80/pull/2534.
> Update glew in sdl-gpu so AddressSanitizer doesn't error out on it; switch to my fork for it

- src/studio/screens/console.c
There was an issue in the code that meant autocomplete on aliases such as `rm` were not working (think this only affects `rm` for now.)
Fixes https://github.com/nesbox/TIC-80/issues/2529.
> Fix autocomplete on command aliases

- build/janet/janetconf.h
- demos/janetdemo.janet
also removed the `strict: true` from the demo cart, which was incorrectly copy/pasted from the fennel demo cart.
> bump Janet version to v1.34

- src/studio/fs.c
- src/studio/fs.h
- src/studio/screens/surf.c
Fulfilling suggestion by @Skeptim from issue 2530 https://github.com/nesbox/TIC-80/issues/2530
**edit** I should probably elaborate...
Opens access to the `isRoot` function already available in `fs.c`. Then checks against it every Backspace or B button press while in `surf.c`. Switches to Console Mode if true, continues normal `goBackDir` if false.
> Gamepad shortcut to exit surf

- README.md
* Added 22.04, 24.04
* Removed 14.04 and 18.04 since they're ancient at this point
> Readme improvements (Ubuntu 22.04, 24.04)

- src/studio/screens/start.c
Another thing that trips up Clang 18 that earlier versions were more forgiving with otherwise.
> `#include` `mach-o/dyld.h` on macOS for `_NSGetExecutablePath`

- src/system/sdl/main.c
Some keyboards send KEY_DOWN/KEY_UP immediately in
sequence to support things like dual-purpose keys.
This change updates the SDL key handler to detect
when a key is pressed and released within a single
frame, and to propagate that key's state as down
for the duration of the frame, rather than just
drop the event entirely.
Fixes https://github.com/nesbox/TIC-80/issues/2156, for SDL
> SDL: don't ignore briefly pressed keys

- src/studio/fs.c
[There is a bug](https://stackoverflow.com/questions/32452777/visual-c-2015-express-stat-not-working-on-windows-xp) in the toolchain we use for the Windows XP builds that makes stat not work and give false errors. The recommended solution is to use `GetFileAttributesEx` instead. The cleanest way I see for it is to create a shim that maps to stat and conditionally #include it.
Tested on a Windows XP VM, freshly compiled on Windows 11 with the `v141_xp` toolchain and works.
Fixes https://github.com/nesbox/TIC-80/issues/1844, https://github.com/nesbox/TIC-80/issues/2357, https://github.com/nesbox/TIC-80/issues/1924.
> Fix the error 'folder <folder> doesn't exist' under Windows XP (win32 build)

- src/studio/system.h
`surf` defaults to HTTPS however the TIC-80 website uses a modern certificate that's not available (by default at least) on old systems, thus we default to plain `http` on the 32-bit build.
Tested on a Thinkpad x220 running Windows XP (32-bit) / Windows 7 (32-bit).
Old build on the left, fix on the right.
> Fix `surf` on win32 builds

- src/studio/screens/console.c
- src/studio/screens/mainmenu.c
Here is my first PR, after all this time ^^.
It contains several improvements of the help content.
* Addition of capital letters to commands help to be consistent with API help.
* I removed the `…` from import and export help messages because of https://github.com/nesbox/TIC-80/issues/2289#issuecomment-1703765551
* Addition of a few command hotkeys
* Addition of details that seemed important to me
* Addition of `\n` in button table because it's missing when we export help
> Help improvements

- src/studio/studio.h
The version of `argparse` you're pinned to wants `int`-s when `ARGPARSE_OPT_BOOLEAN` is used: https://github.com/cofyc/argparse/blob/0d5f5d0745df14a3f373f7eed85bf524714f4524/argparse.c#L57-L66 but you're using `bool`-s: https://github.com/nesbox/TIC-80/blob/main/src/studio/studio.h#L71-L81
If there's a size-mismatch between `bool` and `int` (depending on compiler, platform, etc etc), then whatever garbage may be in the padding gets treated as part of the `int` - I suspect this is why command line fullscreen hasn't worked for a loooooong time now.
> fix horribly broken command line parsing

- src/core/core.c
More discreet and precise fix for issue 2561 (https://github.com/nesbox/TIC-80/issues/2561)
An Excerpt of the changes proposed in PR 2571 (https://github.com/nesbox/TIC-80/pull/2571)
> adds gamepad state being reset

- src/studio/studio.c
By default, devmode is disabled and we will see the game menu, but if you enable it in settings or add the dev mode: on meta tag, the game menu will not be shown.
> #1950: added 'devmode: on' metatag to disable game menu

- cmake/libretro.cmake
I'm unsure if this is the correct approach, but I've updated the cmake definition for libretro to construct a list of language libraries to static link against. Found that on some platforms, since JS was disabled, it wasn't able to find libquickjs.a, so hopefully this fixes it.
> libretro: Update the list of static language libraries

- src/studio/screens/console.c
Add hotkeys topic to help command
Solves the first item of https://github.com/nesbox/TIC-80/issues/1433
Note that the hotkeys will have to be updated manually when they are modified.
Here is the `export help` output
[test_hotkeys-help.md](https://github.com/nesbox/TIC-80/files/15401236/test_hotkeys-help.md)
> Hotkeys topic in help

- build/android/app/src/main/java/org/libsdl/app/SDLActivity.java
Update SDLActivity.java so that the arrow keys are processed first then the joystick.
> Fix for Arrow keys not working on android.

- CMakeLists.txt
- cmake/core.cmake
- cmake/libretro.cmake
There are a few platforms that when `BUILD_STATIC` is enabled, require not linking zlib. Hopefully with an option to toggle disabling it, it will clean up this cmake config a bit.
> libretro: Add `BUILD_WITH_ZLIB` option to allow disabling zlib link

- README.md
* Updated msys2/mingw instructions for Windows
* Added `-DBUILD_WITH_ALL=On` to the instructions
* misc fixes
> Update MSYS2/MINGW build instructions; misc updates

- src/api/fennel.c
- src/studio/screens/console.c
When resuming, you can pass "reload" as the argument, which causes the cart's code to be reloaded before resuming the game.
This allows for a much smoother iterative development style where you can pause the game, make changes, and see the effect of those changes without restarting the game. It does require some special handling in the cart to support saving state to a global and avoiding that state being reinitialized if it's already set; for instance:
state = state or {x=25, y=100, shots={}}
This implements the reload method for the Lua and Fennel scripts, but it will need to be implemented for other scripts independently.
> Implement "resume reload" command.

- src/studio/editors/map.c
Fixes: https://github.com/nesbox/TIC-80/issues/2515
Also makes shift behave the same as clicking with the mouse the tiles menu, this way there's no need to keep holding the shift key to select tiles.
> Fix changing tile in map editor changes tool + not needing to hold shift to show tiles

- src/studio/screens/console.c
Fixes: https://github.com/nesbox/TIC-80/issues/2573
> Avoid command from history not fully visible at the bottom

- src/api/python.c
> font() chromakey argument order in python fixed (#2634)

- src/studio/fs.c
Entering a subdirectory more than one level would cause a buffer overflow and crash TIC-80. This bug was originally introduced in https://github.com/nesbox/TIC-80/pull/2648.
> Fix buffer overflow in `tic_fs_changedir`

- include/tic80.h
- src/studio/studio.c
- src/studio/system.h
- src/system/baremetalpi/kernel.cpp
- src/system/n3ds/main.c
- src/system/sdl/main.c
Fixes https://github.com/nesbox/TIC-80/issues/2520. `alt+[grave]12345` is not triggered if an AZERTY layout is set (the user can still use esc + function keys). This allows AZERTY keyboards to fully (as far as I can tell) work with TIC-80.
There is also some groundwork laid for a potential fix of https://github.com/nesbox/TIC-80/issues/1761 in the future, as well as detecting other layouts; this is more work though and definitely a separate PR. Let me know if you'd rather not have this bit and I can dumb it down to strictly detecting AZERTY.
Tested on MacOS 14, Windows 11 and Linux (EndeavourOS/Arch + Wayland + KDE Plasma 6).
Notes for Linux:
* All SDL2 apps, therefore TIC-80 as well run under Xwayland by default. Keyboard layout change detection will only work if done via `setxkbmap` (or …
> Fix TIC-80 when using a French AZERTY layout

- .gitmodules
This updates `sdl-gpu` to the `master` branch of my fork which at this point is in sync with upstream except for a minor fix that's needed to compile it on some systems. 
This also unbreaks Wayland (if TIC-80 is launched with `SDL_VIDEODRIVER=wayland` the first place, that is) partially. I'm saying partially because if the user is using scaling, CRT mode will look off as if it wasn't scaled. I have yet to track down the exact source of that issue, but the above is already an improvement.
> Update `sdl-gpu`; unbreak Wayland (partially)

- src/api/wren.c
> add map() with no args to wren api class

- src/api.h
- src/api/janet.c
- src/api/js.c
- src/api/luaapi.c
- src/api/mruby.c
- src/api/python.c
- src/api/scheme.c
- src/api/squirrel.c
- src/api/wasm.c
- src/api/wren.c
- src/core/draw.c
This is an implementation of Paul Heckbert's flood fill, providing the functionality of the QBasic PAINT method. This fills a contiguous area of solid color starting from a seed point.
All languages are supported, but not all languages are tested.
There's a closed/wishlist for this:  #2022
Edit: Actually this isn't quite like QB's PAINT. Continued below.
> flood fill paint function

- .github/workflows/build.yml
- cmake/lua.cmake
This version of lua improves tic80 performance and is compatible with current carts. Here's a performance comparison:
lua 5.3:
lua 5.4:
There's also a lua performance comparison in these articles: 
https://eklausmeier.goip.de/blog/2020/05-14-performance-comparison-pallene-vs-lua-5-1-5-2-5-3-5-4-vs-c
https://muxup.com/2023q2/updating-wrens-benchmarks
Lua 5.4 changes: https://lwn.net/Articles/826134/
> Update lua to latest v5.4

- src/api/mruby.c
This change makes the Ruby mouse() function take coordinates from the core api rather than directly from memory.
Resolves #2695
> Fix ruby mouse coordinates

- src/api/fennel.c
- src/api/luaapi.c
Fennel carts have debug.traceback set to fennel.traceback during initialization, which is a function that uses sourcemaps to convert the traceback data which Lua knows about (with line numbers based on the Lua output from the Fennel compiler) into traceback data based on line numbers in the original source code.
Previously this had no effect because debug.traceback was never actually run; luaapi.c contained a call to the underlying luaL_traceback function instead, which did not know about sourcemaps. Replacing it with a call to debug.traceback allows us to see stack traces that use sourcemap data.
This change should have no effect on Lua carts; only Fennel carts and perhaps Moonscript carts.
Also in this patch we set the filename field when compiling Fennel carts; without this the custom …
> Use debug.traceback for stack traces in Lua-based carts.

- README.md
This pull request closes #2711 and also refactors the _README_ file according to these changes:
- Fixed uneven spacing and indentation
- Updated hyphens to em dashes where applicable
- Capitalized titles
- Removed `https://` from link titles
- Updated the headers structure and table of contents
- Updated _Install Instructions_ to include a no-installation method
> Add openSUSE instructions and refactor README

- .gitmodules
- cmake/pocketpy.cmake
- src/api/python.c
The previous pr is https://github.com/nesbox/TIC-80/pull/2714 (1 month ago)
1. Fix a bug of `random` module which uses a wrong initial seed.
2. Fix [#315](https://github.com/pocketpy/pocketpy/issues/315) about `py_switchvm`.
3. Improve `PK_ENABLE_OS` and add `PK_BUILD_WITH_IPO` to cmake options.
4. Add `conio` module which provides `_kbhit` and `_getch` functions for desktop platforms.
5. Fix `True not False` bug of parser.
6. Fix `**` associativity bug. `2**2**3` now evaluates to 256 instead of 64.
7. Add `__float__` and `__int__` and `__round__`.
8. Add `py_bindstaticmethod`.
9. Fix `str.split`. It behaves the same as cpython now.
10. Fix a bug of closure for generator functions.
11. Support `vec*` unpack, e.g. `x, y = vec2i(1, 2)`.
1. fix some type annotation usage e.g. `int | None`. …
> updated pkpy to v2.0.4

- src/api/luaapi.c
Cherry-picked https://github.com/TASEmulators/BizHawk/commit/87a740d09a9f1284dd8ff9bbf3e9dddec9653693. The uninit read caused problems when compiled under our toolchain with `-O2`, see https://github.com/TASEmulators/BizHawk/issues/4190.
> Lua API: Explicitly zero local array

- src/studio/studio.c
I built TIC-80 from source, with `BUILD_EDITORS` turned off. When I launched it, I noticed that there are 'wrong option type' warnings from argparse. After a little debugging, I found that `OPT_END` in the option list was under an `#ifdef`. So when I was building without editors, the list was unterminated.
I fixed this by moving `OPT_END` out of the `#ifdef`.
> Fix OPT_END() missing without BUILD_EDITORS flag

- CMakeLists.txt
- cmake/argparse.cmake
- cmake/gif.cmake
- cmake/janet.cmake
- cmake/lua.cmake
- cmake/mruby.cmake
- cmake/naett.cmake
- cmake/png.cmake
- cmake/quickjs.cmake
- cmake/sdl.cmake
- cmake/squirrel.cmake
- cmake/wasm.cmake
- cmake/zip.cmake
- cmake/zlib.cmake
Hello, I'd like to package tic80 for a Linux distro (GNU Guix), which prefer use system libraries instead of vendor ones.
So here is a patch to introduce a `PREFER_SYSTEM_LIBRARIES` cmake option, when ON it will try to use system ones and fallback to vendor.
> Allow build with system libraries

- README.md
Fix build instructions for Ubuntu 24.04 as informed in issue #2742
> Update Ubuntu 24.04 build instructions

- README.md
**Is your feature request related to a problem? Please describe.** I visited https://github.com/nesbox/TIC-80 and thought your Android app is only available for desktop devices. Browsing this repository respectively the docs I noticed it is available on F-Droid,  too.
**Describe the solution you'd like**
It would be great to have a download button or at least a link on your download page at 
Herr you can get a download badge: https://fdroid.gitlab.io/artwork/badge/get-it-on.png
I have directly used it for the link here, unfortunately needs HTML for [resizing](https://stackoverflow.com/q/24383700/5008962).
Best would be to also add it to the website, for even more visibility.
> Add F-Droid download badge

- src/system/libretro/tic80_libretro.c
Should solve the cursor not showing in some games #2147 and the cursor trailing bug (also mentioned in that issue).
I have also set the cursor to start hidden before the first move. Otherwise we have to wait the first 5 seconds to it to hide in case we want to take screenshots of the game.
> Libretro cursorfix

- build/html/export.html
- build/html/index.html
- build/webapp/index.html
Safari/WebKit sometimes reports physical Arrow keys with KeyboardEvent.location === 3 (numpad). The Emscripten input glue ignores those for directional input, so arrows don't work in Safari.
This PR adds a small, WebKit-scoped capture-phase shim to remap Arrow key events with location 3 to location 0, prevents page scrolling on Arrow keys while the canvas is focused, and ensures the canvas is focusable and focused on start.
Changes:
- build/html/export.html: add WebKit remap + prevent scroll + focus; add tabindex=0
- build/html/index.html: same as above for the basic player
- build/webapp/index.html: same as above for the webapp
Tested locally in Safari: arrows now reach the game.
The preceding text and the patch written by Claude, but the fix does work.
> [web export] Fix Safari Arrow keys in HTML export/webapp
